CREATE TABLE classif_boychenko_cone_liquidity_consistency
(
    id                             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boychenko_cone_immersion_depth float4,
    cb_consistency                  float4
);

INSERT INTO classif_boychenko_cone_liquidity_consistency VALUES (1, 1, -0.27);
DROP TABLE classif_boychenko_cone_liquidity_consistency;