-- вероятно, не используется

CREATE TABLE classif_water_group
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_number int,
    og_1 varchar,
    og_2 varchar,
    og_3 varchar,
    kf float
);