CREATE TABLE classif_peat_decay_degree
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    P250  int,
    value float4
);

INSERT INTO classif_peat_decay_degree VALUES (1, 10, 4.8);
INSERT INTO classif_peat_decay_degree VALUES (2, 11, 5.2);
INSERT INTO classif_peat_decay_degree VALUES (3, 12, 5.5);
INSERT INTO classif_peat_decay_degree VALUES (4, 13, 5.8);
INSERT INTO classif_peat_decay_degree VALUES (5, 14, 6.1);
INSERT INTO classif_peat_decay_degree VALUES (6, 15, 6.5);
INSERT INTO classif_peat_decay_degree VALUES (7, 16, 6.8);
INSERT INTO classif_peat_decay_degree VALUES (8, 17, 7.2);
INSERT INTO classif_peat_decay_degree VALUES (9, 18, 7.6);
INSERT INTO classif_peat_decay_degree VALUES (10, 19, 7.9);

INSERT INTO classif_peat_decay_degree VALUES (11, 20, 8.3);
INSERT INTO classif_peat_decay_degree VALUES (12, 21, 8.7);
INSERT INTO classif_peat_decay_degree VALUES (13, 22, 9.1);
INSERT INTO classif_peat_decay_degree VALUES (14, 23, 9.5);
INSERT INTO classif_peat_decay_degree VALUES (15, 24, 9.9);
INSERT INTO classif_peat_decay_degree VALUES (16, 25, 10.3);
INSERT INTO classif_peat_decay_degree VALUES (17, 26, 10.5);
INSERT INTO classif_peat_decay_degree VALUES (18, 27, 10.7);
INSERT INTO classif_peat_decay_degree VALUES (19, 28, 11.5);
INSERT INTO classif_peat_decay_degree VALUES (20, 29, 11.9);

INSERT INTO classif_peat_decay_degree VALUES (21, 30, 12.3);
INSERT INTO classif_peat_decay_degree VALUES (22, 31, 12.8);
INSERT INTO classif_peat_decay_degree VALUES (23, 32, 13.3);
INSERT INTO classif_peat_decay_degree VALUES (24, 33, 13.8);
INSERT INTO classif_peat_decay_degree VALUES (25, 34, 14.3);
INSERT INTO classif_peat_decay_degree VALUES (26, 35, 14.8);
INSERT INTO classif_peat_decay_degree VALUES (27, 36, 15.3);
INSERT INTO classif_peat_decay_degree VALUES (28, 37, 15.8);
INSERT INTO classif_peat_decay_degree VALUES (29, 38, 16.3);
INSERT INTO classif_peat_decay_degree VALUES (30, 39, 16.8);

INSERT INTO classif_peat_decay_degree VALUES (31, 40, 17.3);
INSERT INTO classif_peat_decay_degree VALUES (32, 41, 17.8);
INSERT INTO classif_peat_decay_degree VALUES (33, 42, 18.3);
INSERT INTO classif_peat_decay_degree VALUES (34, 43, 18.9);
INSERT INTO classif_peat_decay_degree VALUES (35, 44, 19.5);
INSERT INTO classif_peat_decay_degree VALUES (36, 45, 20.1);
INSERT INTO classif_peat_decay_degree VALUES (37, 46, 20.7);
INSERT INTO classif_peat_decay_degree VALUES (38, 47, 21.3);
INSERT INTO classif_peat_decay_degree VALUES (39, 48, 21.9);
INSERT INTO classif_peat_decay_degree VALUES (40, 49, 22.5);

INSERT INTO classif_peat_decay_degree VALUES (41, 50, 23.1);
INSERT INTO classif_peat_decay_degree VALUES (42, 51, 23.7);
INSERT INTO classif_peat_decay_degree VALUES (43, 52, 24.3);
INSERT INTO classif_peat_decay_degree VALUES (44, 53, 25.0);
INSERT INTO classif_peat_decay_degree VALUES (45, 54, 25.7);
INSERT INTO classif_peat_decay_degree VALUES (46, 55, 26.4);
INSERT INTO classif_peat_decay_degree VALUES (47, 56, 27.1);
INSERT INTO classif_peat_decay_degree VALUES (48, 57, 27.8);
INSERT INTO classif_peat_decay_degree VALUES (49, 58, 28.5);
INSERT INTO classif_peat_decay_degree VALUES (50, 59, 29.5);

INSERT INTO classif_peat_decay_degree VALUES (51, 60, 29.9);
INSERT INTO classif_peat_decay_degree VALUES (52, 61, 30.6);
INSERT INTO classif_peat_decay_degree VALUES (53, 62, 31.3);
INSERT INTO classif_peat_decay_degree VALUES (54, 63, 32.0);
INSERT INTO classif_peat_decay_degree VALUES (55, 64, 32.8);
INSERT INTO classif_peat_decay_degree VALUES (56, 65, 33.6);
INSERT INTO classif_peat_decay_degree VALUES (57, 66, 34.4);
INSERT INTO classif_peat_decay_degree VALUES (58, 67, 35.2);
INSERT INTO classif_peat_decay_degree VALUES (59, 68, 36.0);
INSERT INTO classif_peat_decay_degree VALUES (60, 69, 36.8);

INSERT INTO classif_peat_decay_degree VALUES (61, 70, 37.6);
INSERT INTO classif_peat_decay_degree VALUES (62, 71, 38.4);
INSERT INTO classif_peat_decay_degree VALUES (63, 72, 39.3);
INSERT INTO classif_peat_decay_degree VALUES (64, 73, 40.2);
INSERT INTO classif_peat_decay_degree VALUES (65, 74, 41.1);
INSERT INTO classif_peat_decay_degree VALUES (66, 75, 42.0);
INSERT INTO classif_peat_decay_degree VALUES (67, 76, 42.9);
INSERT INTO classif_peat_decay_degree VALUES (68, 77, 43.8);
INSERT INTO classif_peat_decay_degree VALUES (69, 78, 44.7);
INSERT INTO classif_peat_decay_degree VALUES (70, 79, 45.6);

INSERT INTO classif_peat_decay_degree VALUES (71, 80, 46.5);
INSERT INTO classif_peat_decay_degree VALUES (72, 81, 47.5);
INSERT INTO classif_peat_decay_degree VALUES (73, 82, 48.5);
INSERT INTO classif_peat_decay_degree VALUES (74, 83, 49.5);
INSERT INTO classif_peat_decay_degree VALUES (75, 84, 50.5);
INSERT INTO classif_peat_decay_degree VALUES (76, 85, 51.5);
INSERT INTO classif_peat_decay_degree VALUES (77, 86, 52.5);
INSERT INTO classif_peat_decay_degree VALUES (78, 87, 53.5);
INSERT INTO classif_peat_decay_degree VALUES (79, 88, 54.5);
INSERT INTO classif_peat_decay_degree VALUES (80, 89, 55.5);

INSERT INTO classif_peat_decay_degree VALUES (81, 90, 56.5);
INSERT INTO classif_peat_decay_degree VALUES (82, 91, 57.6);
INSERT INTO classif_peat_decay_degree VALUES (83, 92, 58.7);
INSERT INTO classif_peat_decay_degree VALUES (84, 93, 59.8);
INSERT INTO classif_peat_decay_degree VALUES (85, 94, 60.9);
INSERT INTO classif_peat_decay_degree VALUES (86, 95, 62.0);
INSERT INTO classif_peat_decay_degree VALUES (87, 96, 63.2);
INSERT INTO classif_peat_decay_degree VALUES (88, 97, 64.4);
INSERT INTO classif_peat_decay_degree VALUES (89, 98, 65.6);
INSERT INTO classif_peat_decay_degree VALUES (90, 99, 66.8);


TRUNCATE TABLE classif_peat_decay_degree;