CREATE TABLE classif_hatching
(
    id                             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_code_string                varchar,
    grn_code_int                   int,
    short_name                     varchar,
    hatching_name                  varchar,
    hatching_name_credo_autocad    varchar,
    is_credo_autocad_hatching_only boolean,
    credo_color                    int,
    hatching_credo                 varchar,
    is_repeated                    boolean,
    string_id                      int,
    hatching_code_robur            int,
    hatching_color_robur           int
);


COMMENT ON TABLE classif_hatching IS 'ВА: GLOBAL_SGR, Колонка -> Литология + Консистенция -> Штриховка [14.02.2023]';


COMMENT ON COLUMN classif_hatching.grn_code_string IS 'GRN_KOD (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.grn_code_int IS 'GRN_KOD_NUM, преобр в число (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.short_name IS 'NAME_KRAT, наименование грунта краткое (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.hatching_name IS 'SHTRICH_NAME, название файла штриховки (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.hatching_name_credo_autocad IS 'ACAD, название штриховки в СREDO и в AutoCAD (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.is_credo_autocad_hatching_only IS 'ONLY_CREDO, штриховка есть только в CREDO и в AutoCAD (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.credo_color IS 'COLG, цвет в CREDO (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.hatching_credo IS 'PATT, штриховка в CREDO (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.is_repeated IS 'IS_POVTOR, штриховка CREDO повторяется в этом списке- нужно для правильного запроса Q_SKV_GRN (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.string_id IS 'STR_Id, № штриховки-строка в этой тбл (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.hatching_code_robur IS 'R_SHTRIH, код штриховки в ROBUR (таблица ВА) [14.02.2023]';
COMMENT ON COLUMN classif_hatching.hatching_color_robur IS 'R_COLOR, цвет в ROBUR (таблица ВА) [14.02.2023]';


INSERT INTO classif_hatching (grn_code_string, grn_code_int, short_name, hatching_name, hatching_name_credo_autocad,
                               is_credo_autocad_hatching_only, credo_color, hatching_credo, is_repeated, string_id,
                               hatching_code_robur, hatching_color_robur)
VALUES ('1', 1, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);

INSERT INTO classif_hatching (grn_code_string, grn_code_int, short_name, hatching_name, hatching_name_credo_autocad,
                               is_credo_autocad_hatching_only, credo_color, hatching_credo, is_repeated, string_id)
VALUES ('2', 2, 'насыпные грунт', 'NASYP', 'TEHNO', false, 7, '126,189,219,231,231,219,189,126', false, 35);

INSERT INTO classif_hatching (grn_code_string, grn_code_int, short_name, hatching_name, hatching_name_credo_autocad,
                               is_credo_autocad_hatching_only, credo_color, hatching_credo, is_repeated, string_id)
VALUES ('3', 3, 'намывные грунт', 'NAMYV', 'NAMYV', false, 11, '126,189,219,231,231,219,189,126', false, 36);


VALUES ('3', 3, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('4', 4, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('5', 5, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('6', 6, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('7', 7, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('8', 8, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('9', 9, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);
VALUES ('10', 10, 'почв.-раст.сл.', 'POCHVA', 'POCHVA', false, 3, '255,255,255,255,255,255,255,255', false, 34, 66, 1);

4	4	торфы	TORTH	TORTH	FALSE	8	175,175,175,7,255,7,255,255	FALSE	37	72	6
5	5	илы, иловатост	IL	IL	FALSE	2	255,255,255,255,255,183,79,255	FALSE	38	52
6	6	илы  глинистые	IL_GLIN	IL_GLIN	FALSE	2	255,255,253,195,191,0,255,255	FALSE	39	52
7	7	илы суглинистые	IL_SUGL	IL_SUGL	FALSE	2	254,253,251,247,239,223,178,105	FALSE	40	52
8	8	илы супесчаные	IL_SUPS	IL_SUPS	FALSE	2	255,255,255,247,239,198,153,127	FALSE	41	52
9	9	пески гравел	PESOK_G	PESOK_G	FALSE	9	255,255,255,255,255,239,255,255	FALSE	42	64	1
10	10	пески крупн	PESOK_K	PESOK_K	FALSE	9	255,255,255,255,255,239,255,255	FALSE	43	61	1
11	11	пески средн	PESOK_S	PESOK_S	FALSE	9	255,255,255,255,255,239,255,255	FALSE	44	64	1
12	12	пески мелкие	PESOK_M	PESOK_M	FALSE	9	255,255,255,255,255,239,255,255	FALSE	45	62	1
13	13	пески пылеват	PESOK_P	PESOK_P	FALSE	9	255,255,255,255,255,239,255,255	FALSE	46	64	1
14	14	супеси	SUPES	SUPES_D	FALSE	5	255,255,255,247,239,223,191,127	FALSE	47	70	2
15	15	супеси моренные- credo	SUPES	supes_m	TRUE	5	255,255,255,247,239,223,191,127	FALSE	48	70	2
16	16	суглинки	SUGL	SUGL_D	FALSE	6	254,253,251,247,239,223,191,127	FALSE	49	68	3
17	17	суглинок лент.- credo	SUGL_L	SUGL_L	FALSE	6	254,253,251,247,239,223,191,127	FALSE	1	68	3
18	18	глины	GL_DR	GL_DR	FALSE	4	255,255,0,255,255,255,255,255	FALSE	2	36	4
19	19	глины ленточне- credo	GL_DR	GL_L	TRUE	4	255,255,0,255,255,255,255,255	FALSE	3	36	4
20	20	гравийные гр.- credo	GRAVIY	GR_GR	TRUE	7	255,255,255,255,255,255,255,255	FALSE	4	48	5
21	21	щебенистый гр- credo	SCHEBEN	SCH_GR	TRUE	8	255,255,255,255,255,255,255,255	FALSE	5	48	5
22	22	щебень	SCHEBEN	SCHEBEN	FALSE	3	255,255,255,255,255,255,255,255	FALSE	6
23	23	дресва	DRESVA	DR_GR	FALSE	3	255,255,255,255,255,255,255,255	FALSE	7
24	24	галька	GALKA	GALKA	FALSE	3	255,255,255,255,255,255,255,255	FALSE	8	48	5
25	25	гравий	GRAVIY	GRAVIY	FALSE	3	255,255,255,255,255,255,255,255	FALSE	9	48	5
26	26	валуны	VALUNY	VALUNY	FALSE	3	255,255,255,255,255,255,255,255	FALSE	10	48	5
27	27	камни, глыбы- credo	VALUNY	KAMNI	FALSE	3	255,255,255,255,255,255,255,255	FALSE	11
28	28	известняки	IZVEST	IZVEST	FALSE	15	255,255,255,255,255,255,255,255	FALSE	12
29	29	доломиты- credo	dol+glin	DOLOMIT	TRUE	15	255,255,255,255,255,255,255,255	FALSE	13
30	30	алевролиты- credo	DR_GR	ALEVRO	TRUE	15	255,255,255,255,255,255,255,255	FALSE	14
31	31	аргиллиты- credo	DR_GR	ARGILL	TRUE	15	255,255,255,255,255,255,255,255	FALSE	15
32	32	гипс- credo	DR_GR	GIPS	TRUE	15	255,255,255,255,255,255,255,255	FALSE	16
33	33	песчаники	PESCH	PESCH	FALSE	12	255,255,255,255,255,255,255,255	FALSE	17
34	34	граниты	GRANIT	GRANIT	FALSE	8	255,255,255,255,255,255,255,255	FALSE	18
35	35	сиениты- credo	DR_GR	SIENIT	TRUE	8	255,255,255,255,255,255,255,255	FALSE	19
36	36	грав+галечн	grav+galech	GRAVEL_gr	FALSE	3	255,255,255,255,255,255,255,255	FALSE	20	48	5
37	37	сугл+грав	sugl+grav	sugl+grav	FALSE	6	254,253,251,247,239,223,191,127	FALSE	21	70	3
46	38	сугл+грав2	sugl+grav2	sugl+grav2	FALSE	6	254,253,251,247,239,223,191,127	FALSE	29
38	39	супесь+грав	sup+grav	sup+grav	FALSE	5	255,255,255,247,239,223,191,127	FALSE	22	70	3
47	40	суп+грав2	sup+grav2	sup+grav2	FALSE	6	255,255,255,247,239,223,191,127	FALSE	30
39	41	пески+грав	pesk+grav	grav1	FALSE	9	255,255,255,255,255,239,255,255	FALSE	23	64	1
41	43	сланец глин	SlanecGl	slanc_gl	FALSE	0	255,255,255,255,255,255,255,255	FALSE	24
42	44	глина+известн.	GL_IZV	IZVEST	FALSE	0	255,255,255,255,255,255,255,255	TRUE	25	36	4
43	45	доломит+глина	dol+glin	DOLOMIT	FALSE	0	255,255,255,255,255,255,255,255	TRUE	26
44	46	насыпные- credo	NASYP	NASYP	FALSE	0		FALSE	27
45	47	сугл+торф	sugl+torth	sugl_zatorf1	FALSE	6	254,253,251,247,239,223,191,127	FALSE	28
48	48	глина+торф	glina+torth	zatorf2	FALSE	0	255,255,255,255,255,255,255,255	FALSE	31
49	49	песок+торф	PESOK+torf	zatorf1	FALSE	9	255,255,255,255,255,239,255,255	FALSE	32
50	50	сугл.лент.	SUGL_L	sgl_lmgt	FALSE	0		FALSE	33	68	3
