CREATE TABLE classif_weighing_bottle
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar,
    weight float4,
    is_active boolean
);

ALTER TABLE classif_weighing_bottle ADD COLUMN is_active boolean;

COMMENT
ON TABLE classif_weighing_bottle IS 'Номера и веса пустых бюксов [10.04.2023]';

INSERT INTO classif_weighing_bottle (number, weight)
values ('1', 21.2);
INSERT INTO classif_weighing_bottle (number, weight)
values ('1*', 26.83);
INSERT INTO classif_weighing_bottle (number, weight)
values ('10', 21.17);
INSERT INTO classif_weighing_bottle (number, weight)
values ('10*', 2.75);
INSERT INTO classif_weighing_bottle (number, weight)
values ('100', 21.22);