CREATE TABLE classif_ring (
                              id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              number varchar UNIQUE,
    --todo.txt что такое d1, d2, h?
                              d1 int,
                              d2 int,
                              h float4,
                              volume float4,
                              weight float4,
                              is_active boolean
);

COMMENT ON TABLE classif_ring IS 'Классификатор режущих колец. ВА: BRingV [15.04.2023]';

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('1', 0, 0, 34.87, 139.35, 70.72);

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('10', 0, 0, 34.9, 138.38, 84.28);

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('100', 0, 0, 0, 0, 0);

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('101', 0, 0, 34.4, 139.1, 74.95);

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('102', 0, 0, 34.73, 139.88, 54.71);

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('103', 0, 0, 0, 0, 0);

INSERT INTO classif_ring (number, d1, d2, h, volume, weight)
VALUES ('104', 0, 0, 34.28, 138.34, 53.79);

ALTER TABLE classif_ring ADD COLUMN is_active boolean;