-- есть еще какая-то таблица "Описание ИГЭ"
CREATE TABLE ege
(
    id                           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                   int     REFERENCES project (id) ON DELETE SET NULL,
    number                       varchar NOT NULL,
--     Следующие два поля просто цифры по порядку, не понятно, нужно ли это вообще:
    code                         varchar,
    code_number                  int,
    short_name                   varchar,
    description_credo_formular   varchar,

    genesis_id                   int     REFERENCES classif_genesis (id) ON DELETE SET NULL,
--     genesis_description          varchar REFERENCES genesis (gi_name) ON DELETE SET NULL,
--     water_depth                  float4,
    description_kga              varchar,
    description_for_organisation varchar,
--     hatching_name_credo_autocad  varchar, - удалено
    hatching_id int REFERENCES classif_hatching(id) ON DELETE SET NULL,
--     consistency                  varchar, - удалено
    consistency_id int REFERENCES classif_consistency(id) ON DELETE SET NULL,

--     ВА: для формуляр (назначение пока не ясно):
    soil_kind_enum               varchar,

    SSA1                         int,
    SSA2                         int,
    SSA3                         int,
    SSA4                         int,
    SSA5                         int,
    SSA6                         int,
    SSA7                         int,
    SSA8                         int,
    SSA9                         int,
    SSA10                        int,
    SSA11                        int,
    SSA12                        int,

    SS1                          int,
    SS2                          int,
    SS3                          int,
    SS4                          int,
    SS5                          int,
    SS6                          int,
    SS7                          int,
    SS8                          int,
    SS9                          int,
    SS10                         int,
    SS11                         int,
    SS12                         int,
    SS13                         int,
    SS14                         int,
    SS15                         int,
    SS16                         int,
    SS17                         int,
    SS18                         int,
    SS19                         int,
    SS20                         int,

    --     SSA1
--     SSA2
--     SSA3
--     SSA4
--     SSA5
--     SSA6
--     SSA7
--     SSA8
--     SSA9
--     SSA10
--     SSA11
--     SSA12

    soil_class_id                int     REFERENCES cl_soil_class (id) ON DELETE SET NULL,
    soil_kind_id                 int     REFERENCES cl_soil_kind (id) ON DELETE SET NULL,

    color                        int     REFERENCES cl_color (id) ON DELETE SET NULL,
--     След.два поля назначение пока не ясно, связаны с формуляром:
    GB_NMB                       int,
    F_Opis                       varchar,
--     это скрытые поля на форме:
    credo_color int,
    hatching_credo varchar,

-- вод нас с гл
        f_G float4,

    soil_class_kind_group int REFERENCES classif_soil_class_kind_group (id) ON DELETE SET NULL,

    is_archive boolean
);

--   No
-- + GRN_KOD
-- +    GRN_KOD_NUM
-- +    NAME_KRAT
-- +     GENG
-- +    IGENAME
-- +    NAME_POLN
--     i_Leg
--     i_A
--     i_B
--     i_C
--     i_D
--     i_E
--     i_F
--     i_G
-- + f_G - вод нас с гл
--     i_Grng
--     i_H1
--     i_H2
--     i_H3
--     i_H4
--     i_H5
--     i_H6
-- + Opis
-- + ACAD - классификатор classif_hatching
-- + TCNS - классификатор classif_consistency
-- + COLG - из таблицы GLOBAL_SGR, у нас - Hatching, credoColor
-- + PATT - из таблицы GLOBAL_SGR, у нас - Hatching, hatchingCredo
--   cred
--   kga
--   i_tiks
-- - Description
-- + GrName

-- + SS1
-- + SS2
-- + SS3
-- + SS4
-- + SS5
-- + SS6
-- + SS7
-- + SS8
-- + SS9
-- + SS10
-- + SS11
-- + SS12
-- + SS13
-- + SS14
-- + SS15
-- + SS16
-- + SS17
-- + SS18
-- + SS19
-- + SS20

-- + SSA1
-- + SSA2
-- + SSA3
-- + SSA4
-- + SSA5
-- + SSA6
-- + SSA7
-- + SSA8
-- + SSA9
-- + SSA10
-- + SSA11
-- + SSA12

-- - GI - не требуется, т.к. это, видимо, ID генезиса, который уже реализован в колонке genesis_id
-- + SC
-- + SK
-- + SG - колонка SK_GROUP из таблицы cl_soil_kind - сделал для нее также отдельную таблицу
--     SCOSN
--     SKOSN
--     SGOSN
-- +    SSA
--     IS_OSN
-- + COLOR
--     GB_NMB
--     F_Opis - наименование грунта по классиф. Формуляр

ALTER TABLE ege ADD COLUMN consistency_id int REFERENCES classif_consistency(id) ON DELETE SET NULL;

ALTER TABLE ege
    ALTER COLUMN SSA1 TYPE int USING ssa1::integer;
ALTER TABLE ege
    ALTER COLUMN SSA2 TYPE int USING ssa2::integer;
ALTER TABLE ege
    ALTER COLUMN SSA3 TYPE int USING ssa3::integer;
ALTER TABLE ege
    ALTER COLUMN SSA4 TYPE int USING ssa4::integer;
ALTER TABLE ege
    ALTER COLUMN SSA5 TYPE int USING ssa5::integer;
ALTER TABLE ege
    ALTER COLUMN SSA6 TYPE int USING ssa6::integer;
ALTER TABLE ege
    ALTER COLUMN SSA7 TYPE int USING ssa7::integer;
ALTER TABLE ege
    ALTER COLUMN SSA8 TYPE int USING ssa8::integer;
ALTER TABLE ege
    ALTER COLUMN SSA9 TYPE int USING ssa9::integer;
ALTER TABLE ege
    ALTER COLUMN SSA10 TYPE int USING ssa10::integer;
ALTER TABLE ege
    ALTER COLUMN SSA11 TYPE int USING ssa11::integer;
ALTER TABLE ege
    ALTER COLUMN SSA12 TYPE int USING ssa12::integer;





ALTER TABLE ege
    ADD COLUMN color int REFERENCES cl_color (id) ON DELETE SET NULL;

ALTER TABLE ege
    DROP COLUMN color;


ALTER TABLE ege
    ALTER COLUMN number SET NOT NULL;

ALTER TABLE ege
    RENAME COLUMN soil_kind TO soil_kind_enum;

ALTER TABLE ege
    ADD COLUMN project_id int REFERENCES project (id);

ALTER TABLE ege
    ADD COLUMN soil_class_kind_group int REFERENCES classif_soil_class_kind_group (id) ON DELETE SET NULL;



ALTER TABLE ege
    ADD COLUMN  credo_color int;
ALTER TABLE ege
    ADD COLUMN  hatching_credo varchar;

ALTER TABLE ege
    ADD COLUMN f_G float4;
COMMENT ON COLUMN ege.f_G IS 'BA: с гл.хх м -насыщ водой';

ALTER TABLE ege
    ADD COLUMN soil_class_id int REFERENCES cl_soil_class (id) ON DELETE SET NULL;
ALTER TABLE ege
    ADD COLUMN soil_kind_id int REFERENCES cl_soil_kind (id) ON DELETE SET NULL;

-- ALTER TABLE ege
--     ADD COLUMN soil_group_type_id int REFERENCES cl_soil_group_type (id) ON DELETE SET NULL;

ALTER TABLE ege
    ADD COLUMN SS1 int;
ALTER TABLE ege
    ADD COLUMN SS2 int;
ALTER TABLE ege
    ADD COLUMN SS3 int;
ALTER TABLE ege
    ADD COLUMN SS4 int;
ALTER TABLE ege
    ADD COLUMN SS5 int;
ALTER TABLE ege
    ADD COLUMN SS6 int;
ALTER TABLE ege
    ADD COLUMN SS7 int;
ALTER TABLE ege
    ADD COLUMN SS8 int;
ALTER TABLE ege
    ADD COLUMN SS9 int;
ALTER TABLE ege
    ADD COLUMN SS10 int;
ALTER TABLE ege
    ADD COLUMN SS11 int;
ALTER TABLE ege
    ADD COLUMN SS12 int;
ALTER TABLE ege
    ADD COLUMN SS13 int;
ALTER TABLE ege
    ADD COLUMN SS14 int;
ALTER TABLE ege
    ADD COLUMN SS15 int;
ALTER TABLE ege
    ADD COLUMN SS16 int;
ALTER TABLE ege
    ADD COLUMN SS17 int;
ALTER TABLE ege
    ADD COLUMN SS18 int;
ALTER TABLE ege
    ADD COLUMN SS19 int;
ALTER TABLE ege
    ADD COLUMN SS20 int;



COMMENT ON TABLE ege IS 'ВА: CREDO_GRN, Колонка -> Локальный список грунтов. Куча непонятных полей (i_Leg, SS..., SC и т.д.), могут потребоваться в дальнейшем  [18.02.2023]';

COMMENT ON COLUMN ege.number IS 'ВА: IGENAME, № ИГЭ [18.02.2023]';
COMMENT ON COLUMN ege.code IS 'ВА: GRN_KOD [18.02.2023]';
COMMENT ON COLUMN ege.code_number IS 'ВА: GRN_KOD_NUM, преобр в число [18.02.2023]';
COMMENT ON COLUMN ege.short_name IS 'ВА: NAME_KRAT, наименование грунта краткое [18.02.2023]';
COMMENT ON COLUMN ege.description_credo_formular IS 'ВА: NAME_POLN, наименование грунта полное [18.02.2023]';
COMMENT ON COLUMN ege.genesis_id IS 'ВА: GENG, видимо поле такое же как для GI (ВА: фор-генезис), генезис [18.02.2023]';
-- COMMENT ON COLUMN ege.water_depth IS 'ВА: f_G, с гл.хх м -насыщ водой [18.02.2023]';
COMMENT ON COLUMN ege.description_kga IS 'ВА: Opis, наименование грунта по классиф. КГА [18.02.2023]';
COMMENT ON COLUMN ege.hatching_id IS 'ВА: ACAD, для СREDO [18.02.2023]';
COMMENT ON COLUMN ege.consistency_id IS 'ВА: TCNS (консистенция) [18.02.2023]';
--     это скрытые поля на форме:
-- COMMENT ON COLUMN soil_description.credo_color IS 'COLG, цвет в CREDO (таблица ВА) [18.02.2023]';
-- COMMENT ON COLUMN soil_description.hatching_credo IS 'PATT, штриховка в CREDO (таблица ВА) [18.02.2023]';
-- убрал из таблицы, потому что данные будут забираться из таблицы genesis:
-- COMMENT ON COLUMN ege.genesis_description IS 'ВА: Description, генезис словами+ обозн. [18.02.2023]';
COMMENT ON COLUMN ege.description_for_organisation IS 'ВА: GrName, описание для ТИСИЗ [18.02.2023]';
COMMENT ON COLUMN ege.SS1 IS 'ВА: SS1, для Формуляр (назначение пока не ясно) [18.02.2023]';

-- убрал поле - это "вид грунта - быстро". Перенес выпадающий список в окно создания описания КГА
-- COMMENT ON COLUMN ege.soil_kind_enum IS 'ВА: SSA, enum - почва, пески, глинистые [18.02.2023]';
ALTER TABLE ege DROP COLUMN soil_kind_enum;
ALTER TABLE ege ADD COLUMN is_archive boolean;

COMMENT ON COLUMN ege.color IS 'ВА: COLOR [18.02.2023]';
COMMENT ON COLUMN ege.GB_NMB IS 'ВА: GB_NMB, порядок следования слоев -для формуляра (назначение пока не ясно) [18.02.2023]';
COMMENT ON COLUMN ege.F_Opis IS 'ВА: F_Opis, наименование грунта по классиф. Формуляр (назначение пока не ясно) [18.02.2023]';

COMMENT ON COLUMN ege.soil_class_id IS 'ВА: SC, класс [14.11.2023]';
COMMENT ON COLUMN ege.soil_kind_id IS 'ВА: SK, kind [14.11.2023]';

-- не требуется, т.к. это колонка SK_GROUP из таблицы cl_soil_kind
-- COMMENT ON COLUMN ege.soil_group_type_id IS 'ВА: SG, group [14.11.2023]';

INSERT INTO ege (number, code, code_number, short_name, description_credo_formular, genesis_id, description_kga,
                 description_for_organisation, hatching_id, consistency_id, SS1, soil_kind_enum, color,
                 GB_NMB, F_Opis)
VALUES ('', '', 0, '', '', 1, '', '', '', '', 0, 0, '', 0, '');

INSERT INTO ege (number, code, code_number, short_name, description_credo_formular, genesis_id, description_kga,
                 description_for_organisation, hatching_id, consistency_id, SS1, soil_kind_enum, color,
                 GB_NMB, F_Opis)
VALUES ('№ 1', 'G1', 0, 'Test name', '', 1, '', '', '', '', 0, 0, '', 0, '');