CREATE TABLE project
(
    id                                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by                         int     REFERENCES employee (id) ON DELETE SET NULL,
    contract_number                    varchar NOT NULL,
    project_name                       varchar NOT NULL,
    region                             varchar,
    city                               varchar,
    district                           varchar,
    town                               varchar,
    street                             varchar,
    construction_type                  int REFERENCES construction_type (id),
    report_name                        varchar,
    archive_number                     varchar,
    absolute_medium_winter_temperature float4,
    executor                           int     REFERENCES employee (id) ON DELETE SET NULL,
    approver                           int     REFERENCES employee (id) ON DELETE SET NULL,
    projecting_stage                   varchar,
    assignment_date                    date,
    start_date                         date,
    end_date                           date,
    map_point                          int,
    coordinate_x                       float4,
    coordinate_y                       float4,
    is_archive                         boolean
);

ALTER TABLE project
    ADD COLUMN start_date varchar;

ALTER TABLE project
    ADD COLUMN end_date varchar;

ALTER TABLE project
    ADD COLUMN project_name varchar NOT NULL default 'Первый проект';
COMMENT
    ON COLUMN project.project_name IS 'Название проекта/объекта [07.02.2023]';

ALTER TABLE project
    ADD COLUMN is_archive boolean;

COMMENT
    ON COLUMN project.is_archive IS 'Для удаления проекта [01.08.2023]';

ALTER TABLE project
    ALTER
        COLUMN assignment_date TYPE varchar;

ALTER TABLE project
ALTER COLUMN assignment_date TYPE date USING assignment_date::date;

ALTER TABLE project
ALTER COLUMN start_date TYPE date USING start_date::date;

ALTER TABLE project
    ALTER COLUMN end_date TYPE date USING end_date::date;