CREATE TABLE sample
(
    id                                                     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id                                               int NOT NULL REFERENCES survey_point (id) ON DELETE SET NULL,
    labor_number                                           varchar,
    depth_min                                              float4,
    depth_max                                              float4,

    sampling_date varchar,

    average_density                                        float4,
    subterranean_waters_level                              float4,
    structure                                              varchar,
    is_sand                                                boolean,

    particle_density                                       varchar,
    bulk_density                                           varchar,
    dry_soil_density                                       float4,
    dry_soil_density_for_sand_maximal                      float4,
    dry_soil_density_for_sand_minimal                      float4,
    void_ratio                                             float4,
    natural_water_content                                  float4,

    saturation_ratio                                       float4,
    full_water_content                                     float4,

    average_liquid_limit                                   float4,
    average_plastic_limit                                  float4,
    plasticity_index                                       float4,
    liquidity_index                                        float4,

    boychenko_cone_undisturbed_str_immersion_depth_average float4,
    boychenko_cone_broken_str_immersion_depth_average      float4,

    maximal_bulk_density                                   float4,
    maximal_dry_soil_density                               float4,
    optimal_moisture                                       float4,
    coefficient_permeability                               float4,
    rodkf                                                  float4,
    repose_angle_when_dry                                  float4,
    repose_angle_under_water                               float4,

    organic_content                                        float4,
    decomposition_degree                                   float4,
    ash_content                                            float4,

    turing_humus                                           float4,
    soil_softenging_ratio                                  float4,
    rock_decomposition_index                               float4,

    soil_type                                              varchar,
    crushability                                           float4,
    abrasion_resistance                                    float4,
    frost_resistance_grade_one                             float4,
    frost_resistance_grade_two                             float4,
    soil_specific_electrical_resistance                    float4,
    cathode_current_density                                float4,

    passport_attachment                                    varchar,
    passport_list_number                                   int,
    pass_list_CFIKN                                        varchar,
    pass_list_CFIKD                                        varchar,
    pass_attach_CFIKN                                      varchar,
    pass_attach_CFIKD                                      varchar,
    soil_type_for_passport                                 varchar,

    is_archive                                             boolean
);

COMMENT
    ON TABLE sample
    IS 'ВА: Patterns, Лаборатория -> Объект, ввод лабораторных номеров. [25.02.2023]';

COMMENT
    ON COLUMN sample.depth_min IS 'BA: DepthMin, Мин. глубина отбора образца. [25.02.2023]';
COMMENT
    ON COLUMN sample.depth_max IS 'BA: DepthMax, Макс. глубина отбора образца. [25.02.2023]';
COMMENT
    ON COLUMN sample.average_density IS 'BA: DensityAver, Средняя плотность (по двум записям из табл Density). [25.02.2023]';
COMMENT
    ON COLUMN sample.subterranean_waters_level IS 'BA: УрГрВод, уровень грунтовых вод. [25.02.2023]';
COMMENT
    ON COLUMN sample.structure IS 'BA: Структура, нар\ ненаруш. [25.02.2023]';
COMMENT
    ON COLUMN sample.passport_attachment IS 'BA: Пас_прил, паспорт-приложение №. [25.02.2023]';
COMMENT
    ON COLUMN sample.passport_list_number IS 'BA: Пас_лист, паспорт -лист№. [25.02.2023]';
COMMENT
    ON COLUMN sample.pass_list_CFIKN IS 'BA: ListPasCFIKN, для паспорта стабилометра. [25.02.2023]';
COMMENT
    ON COLUMN sample.pass_list_CFIKD IS 'BA: ListPasCFIKD, для паспорта стабилометра. [25.02.2023]';
COMMENT
    ON COLUMN sample.pass_attach_CFIKN IS 'BA: PrilPasCFIKN, для паспорта стабилометра. [25.02.2023]';
COMMENT
    ON COLUMN sample.pass_attach_CFIKD IS 'BA: PrilPasCFIKD, для паспорта стабилометра. [25.02.2023]';
COMMENT
    ON COLUMN sample.soil_type_for_passport IS 'BA: TypeGr, тип грунта для паспорта. [25.02.2023]';

COMMENT
    ON COLUMN sample.particle_density IS 'ВА: RoS, Плотность частиц грунта (Density) [08.03.2023]';

COMMENT
    ON COLUMN sample.bulk_density IS 'ВА: Ro, Плотность грунта (Cut | Paraffin) [08.03.2023]';

COMMENT
    ON COLUMN sample.dry_soil_density IS 'ВА: Rod, Плотность скелета грунта (Cut | Paraffin) [08.03.2023]';

-- todo.txt В ГОСТ 25100-2020 нет такого термина, необходимо проверить корректность этих терминов в программе ВА
COMMENT
    ON COLUMN sample.dry_soil_density_for_sand_maximal IS 'ВА: RodPl, Плотность скелета грунта в пл. сложении [08.03.2023]';

COMMENT
    ON COLUMN sample.dry_soil_density_for_sand_minimal IS 'ВА: RodRih, Плотность скелета грунта в рыхлом сложении [08.03.2023]';

COMMENT
    ON COLUMN sample.void_ratio IS 'ВА: e, Коэффициент пористости (Cut | Paraffin) [08.03.2023]';

COMMENT
    ON COLUMN sample.natural_water_content IS 'ВА: We, Природная влажность(Cut | Paraffin), еще вариант перевода - Water content [08.03.2023]';

-- todo.txt В ГОСТ 25100-2020 нет такого термина, необходимо проверить корректность этих терминов в программе ВА
COMMENT
    ON COLUMN sample.saturation_ratio IS 'ВА: Sr, Коэффициент водонасыщения (Cut | Paraffin) [08.03.2023]';

COMMENT
    ON COLUMN sample.full_water_content IS 'ВА: Wsat, Полная влагоемкость(Cut | Paraffin) [08.03.2023]';

COMMENT
    ON COLUMN sample.average_liquid_limit IS 'ВА: WL, Влажность на границе текучести (Humidity) [08.03.2023]';

COMMENT
    ON COLUMN sample.average_plastic_limit IS 'ВА: Wp, Влажность на границе пластичности (Humidity) [08.03.2023]';

COMMENT
    ON COLUMN sample.plasticity_index IS 'ВА: J, Число пластичности (Humidity) [08.03.2023]';

COMMENT
    ON COLUMN sample.liquidity_index IS 'ВА: IL, Показатель текучести (Humidity) [08.03.2023]';

COMMENT
    ON COLUMN sample.boychenko_cone_broken_str_immersion_depth_average IS 'ВА: Bs, Глубина погружения конуса Бойченко при ненарушенной стр-ре (Cut | Paraffin) [08.03.2023]';

COMMENT
    ON COLUMN sample.boychenko_cone_undisturbed_str_immersion_depth_average IS 'ВА: Bn, Глубина погружения конуса Бойченко при нарушенной стр-ре (Cut | Paraffin) [08.03.2023]';

COMMENT
    ON COLUMN sample.maximal_bulk_density IS 'ВА: RoMax, Max плотность грунта (Consolidation) [08.03.2023]';

COMMENT
    ON COLUMN sample.maximal_dry_soil_density IS 'ВА: RodMax, Max плотность скелета грунта (Consolidation) [08.03.2023]';

COMMENT
    ON COLUMN sample.optimal_moisture IS 'ВА: Wopt, Оптимальная влажность (Consolidation) [08.03.2023]';

COMMENT
    ON COLUMN sample.coefficient_permeability IS 'ВА: Kf, Коэффициент фильтрации [08.03.2023]';

-- todo.txt термин вырван из контекста испытания, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.rodkf IS 'ВА: RodKf, При плотности скелета грунта [08.03.2023]';

-- todo.txt прямой перевод, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.repose_angle_when_dry IS 'ВА: Fi0s, Угол естественного откоса в сухом состоянии [08.03.2023]';

-- todo.txt прямой перевод, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.repose_angle_under_water IS 'ВА: Fi0m, Угол естественного откоса под водой [08.03.2023]';

COMMENT
    ON COLUMN sample.organic_content IS 'ВА: OrgConz, Отн. содержание орг. в-ва [08.03.2023]';

COMMENT
    ON COLUMN sample.decomposition_degree IS 'ВА: Torf_r, Степень разложения торфа [08.03.2023]';

COMMENT
    ON COLUMN sample.ash_content IS 'ВА: Torf_z, Степень зольности торфа [08.03.2023]';

COMMENT
    ON COLUMN sample.turing_humus IS 'ВА: Gum, Гумус по Тюрингу [08.03.2023]';

-- todo.txt ГОСТ 25100-2020, подобран по названию перемнной у ВА, в госте это Кожффициент размягчаемости скального грунта в воде
COMMENT
    ON COLUMN sample.soil_softenging_ratio IS 'ВА: Ksof, Коэффициент разгоняемости [08.03.2023]';

-- todo.txt ГОСТ 25100-2020, термин для коэффициента выветрелости скального грунта, что у ВА нужно уточнить
COMMENT
    ON COLUMN sample.rock_decomposition_index IS 'ВА: Kwr, Коэффициент выветриваемости [08.03.2023]';

-- todo.txt не тип почвы из классификатора? Есть еще поле soil_type_for_passport - это не одно и то же?
-- todo.txt прямой перевод, необходима корректировка во время написания метода, т.к. в названии переменной есть коэффициент выветрелости
COMMENT
    ON COLUMN sample.soil_type IS 'ВА: KwrType, Вид грунта [08.03.2023]';

-- todo.txt прямой перевод, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.crushability IS 'ВА: ProDro, Прочность по дробимости [08.03.2023]';

-- todo.txt прямой перевод, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.abrasion_resistance IS 'ВА: ProIst, Прочность по истираемости [08.03.2023]';

-- todo.txt прямой перевод, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.frost_resistance_grade_one IS 'ВА: Moroz1, Марка по морозостойкости (зам - отт.) [08.03.2023]';

-- todo.txt прямой перевод, необходима корректировка во время написания метода
COMMENT
    ON COLUMN sample.frost_resistance_grade_two IS 'ВА: Moroz2, Марка по морозостойкости (Na2SO4) [08.03.2023]';

-- todo.txt прямой перевод термина Удельное электрическое сопротивление грунта ГОСТ 9.602-2016
COMMENT
    ON COLUMN sample.soil_specific_electrical_resistance IS 'ВА: UESG, Корроз. агр. грунта, Om*m [08.03.2023]';

-- todo.txt прямой перевод термина Плотность катодного тока ГОСТ 9.602-2016
COMMENT
    ON COLUMN sample.cathode_current_density IS 'ВА: PKT, Корроз. агр. грунта, A/m^2 [08.03.2023]';

COMMENT
    ON COLUMN sample.is_sand IS 'Для сводной ведомости грансостава, показать, что это песок в номенклатуре. [15.05.2023]';

ALTER TABLE sample ADD COLUMN sampling_date varchar;