
CREATE TABLE sample
(
    id                                                              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id                                                        int NOT NULL REFERENCES survey_point (id) ON DELETE SET NULL,
    labor_number                                                    varchar,
    depth_min                                                       float4,
    depth_max                                                       float4,
    average_density                                                 float4,
--     ground_water
    subterranean_waters_level                                       float4,
--     todo.txt enum/classif:
-- /structure(наруш/ненаруш/вода/корр/водная вытяжка)
    structure                                                       varchar,

    is_sand                                                         boolean,

    passport_attachment                                             varchar,
    passport_list_number                                            int,
    pass_list_CFIKN                                                 varchar,
    pass_list_CFIKD                                                 varchar,
    pass_attach_CFIKN                                               varchar,
    pass_attach_CFIKD                                               varchar,
    soil_type_for_passport                                          varchar,
    minimum_sampling_depth                                          float4,
    maximum_sampling_depth                                          float4,
    particle_density                                                varchar,
    bulk_density                                                    varchar,
    dry_soil_density                                                float4,
    dry_soil_density_for_sand_maximal                               float4,
    dry_soil_density_for_sand_minimal                               float4,
    void_ratio                                                      float4,
    moisture                                                        float4,
    moisture_by_weighing_bottle                                     float4,
    saturation_ratio                                                float4,
    full_moisture_capacity                                          float4,
    liquid_limit                                                    float4,
    plastic_limit                                                   float4,
    plasticity_index                                                float4,
    liquidity_index                                                 float4,
    boychenko_cone_immersion_depth_with_undisturbed_structure       float4,
    boychenko_cone_immersion_depth_with_broken_structure            float4,
    maximal_bulk_density                                            float4,
    maximal_dry_soil_density                                        float4,
    optimal_moisture                                                float4,
    coefficient_permeability                                        float4,
    rodkf                                                           float4,
    repose_angle_when_dry                                           float4,
    repose_angle_under_water                                        float4,
    organic_content                                                 float4,
    peat_decay_degree                                               float4,
    peat_ash_degree                                                 float4,
    turing_humus                                                    float4,
    soil_softenging_ratio                                           float4,
    rock_decomposition_index                                        float4,
    soil_type                                                       varchar,
    crushability                                                    float4,
    abrasion_resistance                                             float4,
    frost_resistance_grade_one                                      float4,
    frost_resistance_grade_two                                      float4,
    soil_specific_electrical_resistance                             float4,
    cathode_current_density                                         float4,
    -- density
    pycnometer_weight_with_dry_soil_first_measurement               float4,
    empty_pycnometer_weight_first_measurement                       float4,
    pycnometer_weight_with_water_first_measurement                  float4,
    pycnometer_weight_with_soil_and_water_first_measurement         float4,
    dry_soil_weight_first_measurement                               float4,
    soil_volume_first_measurement                                   float4,
    soil_density_first_measurement                                  float4,
    pycnometer_weight_with_dry_soil_second_measurement              float4,
    empty_pycnometer_weight_second_measurement                      float4,
    pycnometer_weight_with_water_second_measurement                 float4,
    pycnometer_weight_with_soil_and_water_second_measurement        float4,
    dry_soil_weight_second_measurement                              float4,
    soil_volume_second_measurement                                  float4,
    soil_density_second_measurement                                 float4,
    --water content
    natural_water_content_weighing_bottle_number_first_measurement  varchar,
    natural_water_content_weighing_bottle_number_second_measurement varchar,
    liquidity_weighing_bottle_number_first_measurement              varchar,
    liquidity_weighing_bottle_number_second_measurement             varchar,
    plastic_weighing_bottle_number_first_measurement                varchar,
    plastic_weighing_bottle_number_second_measurement               varchar,

    natural_water_content_empty_weighing_bottle_mass_first_measur   float4,
    natural_water_content_empty_weighing_bottle_mass_second_measur  float4,
    liquidity_empty_weighing_bottle_mass_first_measurement          float4,
    liquidity_empty_weighing_bottle_mass_second_measurement         float4,
    plastic_empty_weighing_bottle_mass_first_measurement            float4,
    plastic_empty_weighing_bottle_mass_second_measurement           float4,
    natural_water_content_weighing_bottle_with_wet_soil_mass_first  float4,
    natural_water_content_weighing_bottle_with_wet_soil_mass_second float4,
    liquidity_weighing_bottle_with_wet_soil_mass_first              float4,
    liquidity_weighing_bottle_with_wet_soil_mass_second             float4,
    plastic_weighing_bottle_with_wet_soil_mass_first                float4,
    plastic_weighing_bottle_with_wet_soil_mass_second               float4,
    natural_water_content_weighing_bottle_with_dry_soil_mass_first  float4,
    natural_water_content_weighing_bottle_with_dry_soil_mass_second float4,
    liquidity_weighing_bottle_with_dry_soil_mass_first              float4,
    liquidity_weighing_bottle_with_dry_soil_mass_second             float4,
    plastic_weighing_bottle_with_dry_soil_mass_first                float4,
    plastic_weighing_bottle_with_dry_soil_mass_second               float4,
    natural_water_content_weighing_bottle_water_content_first       float4,
    natural_water_content_weighing_bottle_water_content_second      float4,
    liquidity_weighing_bottle_water_content_first                   float4,
    liquidity_weighing_bottle_water_content_second                  float4,
    plastic_weighing_bottle_water_content_first                     float4,
    plastic_weighing_bottle_water_content_second                    float4,
    natural_water_content_average_water_content                     float4,
    liquidity_average_water_content                                 float4,
    plastic_average_water_content                                   float4,
    -- boychenko cone
    undisturbed_str_boychenko_cone_immersion_depth_first_measur     float4,
    undisturbed_str_boychenko_cone_immersion_depth_second_measur    float4,
    undisturbed_str_boychenko_cone_immersion_depth_third_measur     float4,
    broken_str_boychenko_cone_immersion_depth_first_measur          float4,
    broken_str_boychenko_cone_immersion_depth_second_measur         float4,
    broken_str_boychenko_cone_immersion_depth_third_measur          float4,
    undisturbed_str_boychenko_cone_immersion_depth_average          float4,
    broken_str_boychenko_cone_immersion_depth_average               float4,
    -- density ring

    ring_number_first_measurement                                   varchar,
    ring_number_second_measurement                                  varchar,
    empty_ring_mass_first_measurement                               float4,
    empty_ring_mass_second_measurement                              float4,
    ring_with_wet_soil_mass_first_measurement                       float4,
    ring_with_wet_soil_mass_second_measurement                      float4,
    ring_volume_first_measurement                                   float4,
    ring_volume_second_measurement                                  float4,
    ring_density_first_measurement                                  float4,
    ring_density_second_measurement                                 float4,
    ring_density_average                                            float4,
    ring_dry_soil_density                                           float4,
    ring_particle_density                                           float4,
    full_water_content                                              float4,

    -- organic matter

    empty_pot_mass_first_measurement                                float4,
    empty_pot_mass_second_measurement                               float4,
    absolutely_dry_soil_pot_mass_first_measurement                  float4,
    absolutely_dry_soil_pot_mass_second_measurement                 float4,
    calcined_soil_pot_mass_first_measurement                        float4,
    calcined_soil_pot_mass_second_measurement                       float4,
    ignition_loss_mass_first_measurement                            float4,
    ignition_loss_mass_second_measurement                           float4,
    dry_matter_content_before                                       float4,
    dry_matter_content_after                                        float4,
    ignition_loss_average_mass                                      float4,
    ash_content                                                     float4,
    P250                                                            float4,
    decomposition_degree                                            float4,

-- areometric

--     areometric_particle_density                                     float4,
--     areometric_total_subsample                                      float4,
--     areometric_undisturbed_sample_water_content                     float4,
--     areometric_subsample_wet_soil                                   float4,
--
--     areometric_particle_mass_over_10_mm                             float4,
--     areometric_particle_mass_between_10_and_5_mm                    float4,
--     areometric_particle_mass_between_5_and_2_mm                     float4,
--     areometric_particle_mass_between_2_and_1_mm                     float4,
--     areometric_particle_mass_between_1_and_05_mm                    float4,
--     areometric_particle_mass_between_05_and_025_mm                  float4,
--     areometric_particle_mass_between_025_and_01_mm                  float4,
--
--     areometric_total_reading_for_particle_size_between_005_and_001  float4,
--     areometric_total_reading_for_particle_size_between_001_and_0002 float4,
--     areometric_total_reading_for_particle_size_between_less_0002    float4,
--
--     areometric_first_amendment                                      float4,
--     areometric_second_amendment                                     float4,
--     areometric_third_amendment                                      float4,
--     areometric_fourth_amendment                                     float4,
--
--     areometric_weighing_bottle_number                               varchar,
--     areometric_weighing_bottle_mass                                 float4,
--     areometric_bottle_with_wet_soil_mass                            float4,
--     areometric_bottle_with_dry_soil_mass                            float4,
-- todo.txt добавить ограничение в таблицу Sample NOT NULL
    gran_composition_areometry_id                                   int NOT NULL REFERENCES gran_composition_areometry (id) ON DELETE SET NULL


);


ALTER TABLE sample
    ALTER COLUMN point_id SET NOT NULL;

COMMENT ON TABLE sample
    IS 'ВА: Patterns, Лаборатория -> Объект, ввод лабораторных номеров. [25.02.2023]';

COMMENT ON COLUMN sample.depth_min IS 'BA: DepthMin, Мин. глубина отбора образца. [25.02.2023]';
COMMENT ON COLUMN sample.depth_max IS 'BA: DepthMax, Макс. глубина отбора образца. [25.02.2023]';
COMMENT ON COLUMN sample.average_density IS 'BA: DensityAver, Средняя плотность (по двум записям из табл Density). [25.02.2023]';
COMMENT ON COLUMN sample.subterranean_waters_level IS 'BA: УрГрВод, уровень грунтовых вод. [25.02.2023]';
COMMENT ON COLUMN sample.structure IS 'BA: Структура, нар\ ненаруш. [25.02.2023]';
COMMENT ON COLUMN sample.passport_attachment IS 'BA: Пас_прил, паспорт-приложение №. [25.02.2023]';
COMMENT ON COLUMN sample.passport_list_number IS 'BA: Пас_лист, паспорт -лист№. [25.02.2023]';
COMMENT ON COLUMN sample.pass_list_CFIKN IS 'BA: ListPasCFIKN, для паспорта стабилометра. [25.02.2023]';
COMMENT ON COLUMN sample.pass_list_CFIKD IS 'BA: ListPasCFIKD, для паспорта стабилометра. [25.02.2023]';
COMMENT ON COLUMN sample.pass_attach_CFIKN IS 'BA: PrilPasCFIKN, для паспорта стабилометра. [25.02.2023]';
COMMENT ON COLUMN sample.pass_attach_CFIKD IS 'BA: PrilPasCFIKD, для паспорта стабилометра. [25.02.2023]';
COMMENT ON COLUMN sample.soil_type_for_passport IS 'BA: TypeGr, тип грунта для паспорта. [25.02.2023]';

-- todo.txt В таблице ВА - 'Счетчик образцов (Patterns)' - зачем?

-- СводнаяВедомостьВход
-- todo.txt выполнить скрипт:
ALTER TABLE sample
    ADD COLUMN minimum_sampling_depth float4;
COMMENT ON COLUMN sample.minimum_sampling_depth IS 'ВА: DepthMin, Мин. глубина отбора образца (Patterns) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN maximum_sampling_depth float4;
COMMENT ON COLUMN sample.maximum_sampling_depth IS 'ВА: DepthMax, Макс. глубина отбора образца (Patterns) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN particle_density varchar;
COMMENT ON COLUMN sample.particle_density IS 'ВА: RoS, Плотность частиц грунта (Density) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN bulk_density varchar;
COMMENT ON COLUMN sample.bulk_density IS 'ВА: Ro, Плотность грунта (Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN dry_soil_density float4;
COMMENT ON COLUMN sample.dry_soil_density IS 'ВА: Rod, Плотность скелета грунта (Cut | Paraffin) [08.03.2023]';
-- todo.txt В ГОСТ 25100-2020 нет такого термина, необходимо проверить корректность этих терминов в программе ВА
ALTER TABLE sample
    ADD COLUMN dry_soil_density_for_sand_maximal float4;
COMMENT ON COLUMN sample.dry_soil_density_for_sand_maximal IS 'ВА: RodPl, Плотность скелета грунта в пл. сложении [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN dry_soil_density_for_sand_minimal float4;
COMMENT ON COLUMN sample.dry_soil_density_for_sand_minimal IS 'ВА: RodRih, Плотность скелета грунта в рыхлом сложении [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN void_ratio float4;
COMMENT ON COLUMN sample.void_ratio IS 'ВА: e, Коэффициент пористости (Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN moisture float4;
COMMENT ON COLUMN sample.moisture IS 'ВА: We, Природная влажность(Cut | Paraffin), еще вариант перевода - Water content [08.03.2023]';
-- todo.txt В ГОСТ 25100-2020 нет такого термина, необходимо проверить корректность этих терминов в программе ВА
ALTER TABLE sample
    ADD COLUMN moisture_by_weighing_bottle float4;
COMMENT ON COLUMN sample.moisture_by_weighing_bottle IS 'ВА: Wb, Влажность по бюксу (Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN saturation_ratio float4;
COMMENT ON COLUMN sample.saturation_ratio IS 'ВА: Sr, Коэффициент водонасыщения (Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN full_moisture_capacity float4;
COMMENT ON COLUMN sample.full_moisture_capacity IS 'ВА: Wsat, Полная влагоемкость(Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN liquid_limit float4;
COMMENT ON COLUMN sample.liquid_limit IS 'ВА: WL, Влажность на границе текучести (Humidity) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN plastic_limit float4;
COMMENT ON COLUMN sample.plastic_limit IS 'ВА: Wp, Влажность на границе пластичности (Humidity) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN plasticity_index float4;
COMMENT ON COLUMN sample.plasticity_index IS 'ВА: J, Число пластичности (Humidity) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN liquidity_index float4;
COMMENT ON COLUMN sample.liquidity_index IS 'ВА: IL, Показатель текучести (Humidity) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN boychenko_cone_immersion_depth_with_undisturbed_structure float4;
COMMENT ON COLUMN sample.boychenko_cone_immersion_depth_with_undisturbed_structure IS 'ВА: Bs, Глубина погружения конуса Бойченко при ненарушенной стр-ре (Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN boychenko_cone_immersion_depth_with_broken_structure float4;
COMMENT ON COLUMN sample.boychenko_cone_immersion_depth_with_broken_structure IS 'ВА: Bn, Глубина погружения конуса Бойченко при нарушенной стр-ре (Cut | Paraffin) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN maximal_bulk_density float4;
COMMENT ON COLUMN sample.maximal_bulk_density IS 'ВА: RoMax, Max плотность грунта (Consolidation) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN maximal_dry_soil_density float4;
COMMENT ON COLUMN sample.maximal_dry_soil_density IS 'ВА: RodMax, Max плотность скелета грунта (Consolidation) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN optimal_moisture float4;
COMMENT ON COLUMN sample.optimal_moisture IS 'ВА: Wopt, Оптимальная влажность (Consolidation) [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN coefficient_permeability float4;
COMMENT ON COLUMN sample.coefficient_permeability IS 'ВА: Kf, Коэффициент фильтрации [08.03.2023]';
-- todo.txt термин вырван из контекста испытания, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN rodkf float4;
COMMENT ON COLUMN sample.rodkf IS 'ВА: RodKf, При плотности скелета грунта [08.03.2023]';
-- todo.txt прямой перевод, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN repose_angle_when_dry float4;
COMMENT ON COLUMN sample.repose_angle_when_dry IS 'ВА: Fi0s, Угол естественного откоса в сухом состоянии [08.03.2023]';
-- todo.txt прямой перевод, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN repose_angle_under_water float4;
COMMENT ON COLUMN sample.repose_angle_under_water IS 'ВА: Fi0m, Угол естественного откоса под водой [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN organic_content float4;
COMMENT ON COLUMN sample.organic_content IS 'ВА: OrgConz, Отн. содержание орг. в-ва [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN peat_decay_degree float4;
COMMENT ON COLUMN sample.peat_decay_degree IS 'ВА: Torf_r, Степень разложения торфа [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN peat_ash_degree float4;
COMMENT ON COLUMN sample.peat_ash_degree IS 'ВА: Torf_z, Степень зольности торфа [08.03.2023]';
ALTER TABLE sample
    ADD COLUMN turing_humus float4;
COMMENT ON COLUMN sample.turing_humus IS 'ВА: Gum, Гумус по Тюрингу [08.03.2023]';
-- todo.txt ГОСТ 25100-2020, подобран по названию перемнной у ВА, в госте это Кожффициент размягчаемости скального грунта в воде
ALTER TABLE sample
    ADD COLUMN soil_softenging_ratio float4;
COMMENT ON COLUMN sample.soil_softenging_ratio IS 'ВА: Ksof, Коэффициент разгоняемости [08.03.2023]';
-- todo.txt ГОСТ 25100-2020, термин для коэффициента выветрелости скального грунта, что у ВА нужно уточнить
ALTER TABLE sample
    ADD COLUMN rock_decomposition_index float4;
COMMENT ON COLUMN sample.rock_decomposition_index IS 'ВА: Kwr, Коэффициент выветриваемости [08.03.2023]';
-- todo.txt не тип почвы из классификатора? Есть еще поле soil_type_for_passport - это не одно и то же?
-- todo.txt прямой перевод, необходима корректировка во время написания метода, т.к. в названии переменной есть коэффициент выветрелости
ALTER TABLE sample
    ADD COLUMN soil_type varchar;
COMMENT ON COLUMN sample.soil_type IS 'ВА: KwrType, Вид грунта [08.03.2023]';
-- todo.txt прямой перевод, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN crushability float4;
COMMENT ON COLUMN sample.crushability IS 'ВА: ProDro, Прочность по дробимости [08.03.2023]';
-- todo.txt прямой перевод, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN abrasion_resistance float4;
COMMENT ON COLUMN sample.abrasion_resistance IS 'ВА: ProIst, Прочность по истираемости [08.03.2023]';
-- todo.txt прямой перевод, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN frost_resistance_grade_one float4;
COMMENT ON COLUMN sample.frost_resistance_grade_one IS 'ВА: Moroz1, Марка по морозостойкости (зам - отт.) [08.03.2023]';
-- todo.txt прямой перевод, необходима корректировка во время написания метода
ALTER TABLE sample
    ADD COLUMN frost_resistance_grade_two float4;
COMMENT ON COLUMN sample.frost_resistance_grade_two IS 'ВА: Moroz2, Марка по морозостойкости (Na2SO4) [08.03.2023]';
-- todo.txt прямой перевод термина Удельное электрическое сопротивление грунта ГОСТ 9.602-2016
ALTER TABLE sample
    ADD COLUMN soil_specific_electrical_resistance float4;
COMMENT ON COLUMN sample.soil_specific_electrical_resistance IS 'ВА: UESG, Корроз. агр. грунта, Om*m [08.03.2023]';
-- todo.txt прямой перевод термина Плотность катодного тока ГОСТ 9.602-2016
ALTER TABLE sample
    ADD COLUMN cathode_current_density float4;
COMMENT ON COLUMN sample.cathode_current_density IS 'ВА: PKT, Корроз. агр. грунта, A/m^2 [08.03.2023]';



-- Density:
-- плотность
-- todo.txt выполнить скрипт

ALTER TABLE sample
    ADD COLUMN pycnometer_weight_with_dry_soil_first_measurement float4;
COMMENT ON COLUMN sample.pycnometer_weight_with_dry_soil_first_measurement IS 'ВА: X1a, Вес пикнометра с сухим грунтом [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN empty_pycnometer_weight_first_measurement float4;
COMMENT ON COLUMN sample.empty_pycnometer_weight_first_measurement IS 'ВА: X2a, Вес пустого пикнометра (1-е измерение) [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN pycnometer_weight_with_water_first_measurement float4;
COMMENT ON COLUMN sample.pycnometer_weight_with_water_first_measurement IS 'ВА: X3a, Вес пикнометра с водой [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN pycnometer_weight_with_soil_and_water_first_measurement float4;
COMMENT ON COLUMN sample.pycnometer_weight_with_soil_and_water_first_measurement IS 'ВА: X4a, Вес пикнометра с грунтом и водой [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN dry_soil_weight_first_measurement float4;
COMMENT ON COLUMN sample.dry_soil_weight_first_measurement IS 'ВА: X12a, Вес сухого грунта [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN soil_volume_first_measurement float4;
COMMENT ON COLUMN sample.soil_volume_first_measurement IS 'ВА: Va, Объем грунта [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN soil_density_first_measurement float4;
COMMENT ON COLUMN sample.soil_density_first_measurement IS 'ВА: Roa, Плотность грунта [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN pycnometer_weight_with_dry_soil_second_measurement float4;
COMMENT ON COLUMN sample.pycnometer_weight_with_dry_soil_second_measurement IS 'ВА: X1b, Вес пикнометра с сухим грунтом (2-е измерение) [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN empty_pycnometer_weight_second_measurement float4;
COMMENT ON COLUMN sample.empty_pycnometer_weight_second_measurement IS 'ВА: X2b, Вес пустого пикнометра [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN pycnometer_weight_with_water_second_measurement float4;
COMMENT ON COLUMN sample.pycnometer_weight_with_water_second_measurement IS 'ВА: X3b, Вес пикнометра с водой [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN pycnometer_weight_with_soil_and_water_second_measurement float4;
COMMENT ON COLUMN sample.pycnometer_weight_with_soil_and_water_second_measurement IS 'ВА: X4b, Вес пикнометра с грунтом и водой [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN dry_soil_weight_second_measurement float4;
COMMENT ON COLUMN sample.dry_soil_weight_second_measurement IS 'ВА: X12b, Вес сухого грунта [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN soil_volume_second_measurement float4;
COMMENT ON COLUMN sample.soil_volume_second_measurement IS 'ВА: Vb, Объем грунта [20.03.2023]';

ALTER TABLE sample
    ADD COLUMN soil_density_second_measurement float4;
COMMENT ON COLUMN sample.soil_density_second_measurement IS 'ВА: Rob, Плотность грунта [20.03.2023]';


--humidity:

ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_number_first_measurement varchar;
COMMENT ON COLUMN sample.natural_water_content_weighing_bottle_number_first_measurement IS 'Естественная влажность. Номер бюкса. Первое измерение [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_number_second_measurement varchar;
COMMENT ON COLUMN sample.natural_water_content_weighing_bottle_number_second_measurement IS 'Естественная влажность. Номер бюкса. Второе измерение [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_number_first_measurement varchar;
COMMENT ON COLUMN sample.liquidity_weighing_bottle_number_first_measurement IS 'Влажность на границе текучести. Номер бюкса. Первое измерение [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_number_second_measurement varchar;
COMMENT ON COLUMN sample.liquidity_weighing_bottle_number_second_measurement IS 'Влажность на границе текучести. Номер бюкса. Второе измерение [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_number_first_measurement varchar;
COMMENT ON COLUMN sample.plastic_weighing_bottle_number_first_measurement IS 'Влажность на границе раската. Номер бюкса. Первое измерение [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_number_second_measurement varchar;
COMMENT ON COLUMN sample.plastic_weighing_bottle_number_second_measurement IS 'Влажность на границе раската. Номер бюкса. Второе измерение [09.04.2023]';


ALTER TABLE sample
    ADD COLUMN natural_water_content_empty_weighing_bottle_mass_first_measur float4;
COMMENT ON COLUMN sample.natural_water_content_empty_weighing_bottle_mass_first_measur IS 'ВА: X1_a, Вес пустого бюкса [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN natural_water_content_empty_weighing_bottle_mass_second_measur float4;
COMMENT ON COLUMN sample.natural_water_content_empty_weighing_bottle_mass_second_measur IS 'ВА: X1_b, Вес пустого бюкса [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN liquidity_empty_weighing_bottle_mass_first_measurement float4;
COMMENT ON COLUMN sample.liquidity_empty_weighing_bottle_mass_first_measurement IS 'ВА: Y1_a, Вес пустого бюкса [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN liquidity_empty_weighing_bottle_mass_second_measurement float4;
COMMENT ON COLUMN sample.liquidity_empty_weighing_bottle_mass_second_measurement IS 'ВА: Y1_b, Вес пустого бюкса [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN plastic_empty_weighing_bottle_mass_first_measurement float4;
COMMENT ON COLUMN sample.plastic_empty_weighing_bottle_mass_first_measurement IS 'ВА: Z1_a, Вес пустого бюкса [09.04.2023]';

ALTER TABLE sample
    ADD COLUMN plastic_empty_weighing_bottle_mass_second_measurement float4;
COMMENT ON COLUMN sample.plastic_empty_weighing_bottle_mass_second_measurement IS 'ВА: Z1_b, Вес пустого бюкса [09.04.2023]';


ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_with_wet_soil_mass_first float4;

ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_with_wet_soil_mass_second float4;

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_with_wet_soil_mass_first float4;

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_with_wet_soil_mass_second float4;

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_with_wet_soil_mass_first float4;

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_with_wet_soil_mass_second float4;


ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_with_dry_soil_mass_first float4;

ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_with_dry_soil_mass_second float4;

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_with_dry_soil_mass_first float4;

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_with_dry_soil_mass_second float4;

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_with_dry_soil_mass_first float4;

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_with_dry_soil_mass_second float4;


ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_water_content_first float4;

ALTER TABLE sample
    ADD COLUMN natural_water_content_weighing_bottle_water_content_second float4;

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_water_content_first float4;

ALTER TABLE sample
    ADD COLUMN liquidity_weighing_bottle_water_content_second float4;

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_water_content_first float4;

ALTER TABLE sample
    ADD COLUMN plastic_weighing_bottle_water_content_second float4;

--todo.txt заменить на: average water content
ALTER TABLE sample
    ADD COLUMN natural_water_content_average_water_content float4;

--todo.txt заменить на: average liquid limit
ALTER TABLE sample
    ADD COLUMN liquidity_average_water_content float4;

--todo.txt заменить на: average_plastic_limit
ALTER TABLE sample
    ADD COLUMN plastic_average_water_content float4;

-- + выше в sample поле plasticity_index


-- Boychenko cone


ALTER TABLE sample
    ADD COLUMN undisturbed_str_boychenko_cone_immersion_depth_first_measur float4;

ALTER TABLE sample
    ADD COLUMN undisturbed_str_boychenko_cone_immersion_depth_second_measur float4;

ALTER TABLE sample
    ADD COLUMN undisturbed_str_boychenko_cone_immersion_depth_third_measur float4;

ALTER TABLE sample
    ADD COLUMN broken_str_boychenko_cone_immersion_depth_first_measur float4;

ALTER TABLE sample
    ADD COLUMN broken_str_boychenko_cone_immersion_depth_second_measur float4;

ALTER TABLE sample
    ADD COLUMN broken_str_boychenko_cone_immersion_depth_third_measur float4;

ALTER TABLE sample
    ADD COLUMN undisturbed_str_boychenko_cone_immersion_depth_average float4;

ALTER TABLE sample
    ADD COLUMN broken_str_boychenko_cone_immersion_depth_average float4;

-- Ring density

ALTER TABLE sample
    ADD COLUMN ring_number_first_measurement varchar;

ALTER TABLE sample
    ADD COLUMN ring_number_second_measurement varchar;

ALTER TABLE sample
    ADD COLUMN empty_ring_mass_first_measurement float4;

ALTER TABLE sample
    ADD COLUMN empty_ring_mass_second_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_with_wet_soil_mass_first_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_with_wet_soil_mass_second_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_volume_first_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_volume_second_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_density_first_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_density_second_measurement float4;

ALTER TABLE sample
    ADD COLUMN ring_density_average float4;

ALTER TABLE sample
    ADD COLUMN ring_dry_soil_density float4;

COMMENT ON COLUMN sample.ring_dry_soil_density IS 'Плотность скелета. [19.04.2023]';

-- скорее всего это плотность из первого метода (RoSr)
--todo.txt удалить из таблицы
ALTER TABLE sample
    ADD COLUMN ring_particle_density float4;

COMMENT ON COLUMN sample.ring_particle_density IS 'Плотность частиц грунта. [19.04.2023]';

-- такое поле уже есть выше
-- ALTER TABLE sample
--     ADD COLUMN void_ratio float4;
--
-- COMMENT ON COLUMN sample.void_ratio IS 'Коэффициент пористости. [19.04.2023]';

ALTER TABLE sample
    ADD COLUMN full_water_content float4;

COMMENT ON COLUMN sample.full_water_content IS 'Полная влагоемкость. [19.04.2023]';

-- такое поле уже есть выше
-- ALTER TABLE sample
--     ADD COLUMN saturation_ratio float4;
--
-- COMMENT ON COLUMN sample.saturation_ratio IS 'Коэффициент водонасыщения. [19.04.2023]';

-- такое поле уже есть выше
-- ALTER TABLE sample
--     ADD COLUMN liquidity_index float4;
--
-- COMMENT ON COLUMN sample.liquidity_index IS 'Показатель текучести. [19.04.2023]';


-- Organic Matter

ALTER TABLE sample
    ADD COLUMN empty_pot_mass_first_measurement float4;
COMMENT ON COLUMN sample.empty_pot_mass_first_measurement IS 'Вес пустого тигля. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN empty_pot_mass_second_measurement float4;
COMMENT ON COLUMN sample.empty_pot_mass_second_measurement IS 'Вес пустого тигля. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN absolutely_dry_soil_pot_mass_first_measurement float4;
COMMENT ON COLUMN sample.absolutely_dry_soil_pot_mass_first_measurement IS 'Вес тигля с абс. сухим грунтом. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN absolutely_dry_soil_pot_mass_second_measurement float4;
COMMENT ON COLUMN sample.absolutely_dry_soil_pot_mass_second_measurement IS 'Вес тигля с абс. сухим грунтом. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN calcined_soil_pot_mass_first_measurement float4;
COMMENT ON COLUMN sample.calcined_soil_pot_mass_first_measurement IS 'Вес тигля с прокаленным грунтом. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN calcined_soil_pot_mass_second_measurement float4;
COMMENT ON COLUMN sample.calcined_soil_pot_mass_second_measurement IS 'Вес тигля с прокаленным грунтом. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN ignition_loss_mass_first_measurement float4;
COMMENT ON COLUMN sample.ignition_loss_mass_first_measurement IS 'Потери при прокаливании. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN ignition_loss_mass_second_measurement float4;
COMMENT ON COLUMN sample.ignition_loss_mass_second_measurement IS 'Потери при прокаливании. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN dry_matter_content_before float4;
COMMENT ON COLUMN sample.dry_matter_content_before IS 'Доля сухого в-ва. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN dry_matter_content_after float4;
COMMENT ON COLUMN sample.dry_matter_content_after IS 'Доля сухого в-ва. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN ignition_loss_average_mass float4;

ALTER TABLE sample
    ADD COLUMN ash_content float4;
COMMENT ON COLUMN sample.ash_content IS 'Зольность,%. [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN P250 float4;
COMMENT ON COLUMN sample.P250 IS '? [30.04.2023]';

ALTER TABLE sample
    ADD COLUMN decomposition_degree float4;
COMMENT ON COLUMN sample.decomposition_degree IS 'Степень разложения,%. [30.04.2023]';


ALTER TABLE sample
    ADD COLUMN is_sand boolean;
COMMENT ON COLUMN sample.is_sand IS 'Для сводной ведомости грансостава, показать, что это песок в номенклатуре. [15.05.2023]';

-- todo.txt запустить скрипт:
-- areometric

-- ALTER TABLE sample
--     ADD COLUMN areometric_particle_density float4;
-- COMMENT ON COLUMN sample.areometric_particle_density IS 'Для монолитов равна плотности из метода Плотность. Для нарушенных вводится вручную [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_total_subsample float4;
COMMENT ON COLUMN sample.areometric_total_subsample IS 'Общая навеска [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_undisturbed_sample_water_content float4;
COMMENT ON COLUMN sample.areometric_undisturbed_sample_water_content IS 'Влажность монолита [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_subsample_wet_soil float4;
COMMENT ON COLUMN sample.areometric_subsample_wet_soil IS 'Навеска влажного грунта [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_over_10_mm float4;
COMMENT ON COLUMN sample.areometric_particle_mass_over_10_mm IS 'Вес фракции [16.05.2023]';



ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_between_10_and_5_mm float4;

ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_between_5_and_2_mm float4;

ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_between_2_and_1_mm float4;

ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_between_1_and_05_mm float4;

ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_between_05_and_025_mm float4;

ALTER TABLE sample
    ADD COLUMN areometric_particle_mass_between_025_and_01_mm float4;



ALTER TABLE sample
    ADD COLUMN areometric_total_reading_for_particle_size_between_005_and_001 float4;
COMMENT ON COLUMN sample.areometric_particle_mass_over_10_mm IS 'Размер частиц [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_total_reading_for_particle_size_between_001_and_0002 float4;

ALTER TABLE sample
    ADD COLUMN areometric_total_reading_for_particle_size_between_less_0002 float4;


ALTER TABLE sample
    ADD COLUMN areometric_first_amendment float4;
COMMENT ON COLUMN sample.areometric_particle_mass_over_10_mm IS 'Поправки [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_second_amendment float4;

ALTER TABLE sample
    ADD COLUMN areometric_third_amendment float4;
COMMENT ON COLUMN sample.areometric_particle_mass_over_10_mm IS 'Пока задисэйблено [16.05.2023]';

ALTER TABLE sample
    ADD COLUMN areometric_fourth_amendment float4;


ALTER TABLE sample
    ADD COLUMN weighing_bottle_number float4;

ALTER TABLE sample
    ADD COLUMN empty_weighing_bottle_mass float4;

ALTER TABLE sample
    ADD COLUMN weighing_bottle_with_wet_soil_mass float4;

ALTER TABLE sample
    ADD COLUMN weighing_bottle_with_dry_soil_mass float4;

ALTER TABLE sample
    RENAME COLUMN weighing_bottle_number TO areometric_weighing_bottle_number;
ALTER TABLE sample
    RENAME COLUMN empty_weighing_bottle_mass TO areometric_empty_weighing_bottle_mass;
ALTER TABLE sample
    RENAME COLUMN weighing_bottle_with_wet_soil_mass TO areometric_weighing_bottle_with_wet_soil_mass;
ALTER TABLE sample
    RENAME COLUMN weighing_bottle_with_dry_soil_mass TO areometric_weighing_bottle_with_dry_soil_mass;

ALTER TABLE sample
ALTER COLUMN areometric_weighing_bottle_number TYPE varchar;

-- areometric_particle_density float4,
-- areometric_total_subsample float4,
-- areometric_undisturbed_sample_water_content float4,
-- areometric_subsample_wet_soil float4,
--
-- бюкс

--
-- areometric_particle_mass_over_10_mm float4,
-- areometric_particle_mass_between_10_and_5_mm float4,
-- areometric_particle_mass_between_10_and_5_mm float4,
-- areometric_particle_mass_between_5_and_2_mm float4,
-- areometric_particle_mass_between_2_and_1_mm float4,
-- areometric_particle_mass_between_1_and_05_mm float4,
-- areometric_particle_mass_between_05_and_025_mm float4,
-- areometric_particle_mass_between_025_and_01_mm float4,
--
-- areometric_total_reading_for_particle_size_between_005_and_001 float4,
-- areometric_total_reading_for_particle_size_between_001_and_0002 float4,
-- areometric_total_reading_for_particle_size_between_less_0002 float4,
--
-- areometric_first_amendment float4,
-- areometric_second_amendment float4,
-- areometric_third_amendment float4,
-- areometric_fourth_amendment float4


-- emptyPotMassFirstMeasurement
-- emptyPotMassSecondMeasurement
-- absolutelyDrySoilPotMassFirstMeasurement
-- absolutelyDrySoilPotMassFirstMeasurement
-- calcinedSoilPotMassFirstMeasurement
-- calcinedSoilPotMassSecondMeasurement
-- ignitionLossMassFirstMeasurement
-- ignitionLossMassSecondMeasurement
-- dryMatterContentBefore
-- dryMatterContentAfter
-- ignitionLossAverageMass
-- ashContent
-- P250
-- decompositionDegree


-- ring_number_first_measurement varchar,
--
-- ring_number_second_measurement varchar,
--
-- empty_ring_mass_first_measurement float4,
--
-- empty_ring_mass_second_measurement float4,
--
-- ring_with_wet_soil_mass_first_measurement float4,
--
-- ring_with_wet_soil_mass_second_measurement float4,
--
-- ring_volume_first_measurement float4,
--
-- ring_volume_second_measurement float4,
--
-- ring_density_first_measurement float4,
--
-- ring_density_second_measurement float4,
--
-- ring_density_average float4,
--
-- ring_dry_soil_density float4,
--
-- ring_particle_density float4,
--
-- --void_ratio float4;
--
-- full_water_content float4,
--
-- --saturation_ratio float4;
-- --liquidity_index float4;


-- minimum_sampling_depth float4,
-- maximum_sampling_depth float4,
-- particle_density varchar,
-- bulk_density varchar,
-- dry_soil_density float4,
-- dry_soil_density_for_sand_maximal float4,
-- dry_soil_density_for_sand_minimal float4,
-- void_ratio float4,
-- moisture float4,
-- moisture_by_weighing_bottle float4,
-- saturation_ratio float4,
-- full_moisture_capacity float4,
-- liquid_limit float4,
-- plastic_limit float4,
-- plasticity_index float4,
-- liquidity_index float4,
-- boychenko_cone_immersion_depth_with_undisturbed_structure float4,
-- boychenko_cone_immersion_depth_with_broken_structure float4,
-- maximal_bulk_density float4,
-- maximal_dry_soil_density float4,
-- optimal_moisture float4,
-- coefficient_permeability float4,
-- RodKf float4,
-- repose_angle_when_dry float4,
-- repose_angle_under_water float4,
-- organic_content float4,
-- peat_decay_degree float4,
-- peat_ash_degree float4,
-- turing_humus float4,
-- soil_softenging_ratio float4,
-- rock_decomposition_index float4,
-- soil_type varchar,
-- crushability float4,
-- abrasion_resistance float4,
-- frost_resistance_grade_one float4,
-- frost_resistance_grade_two float4,
-- soil_specific_electrical_resistance float4,
-- cathode_current_density float4,