CREATE TABLE role
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar NOT NULL
);

INSERT INTO role (role_name)
VALUES ('Admin');
INSERT INTO role (role_name)
VALUES ('Geologist');
INSERT INTO role (role_name)
VALUES ('Manager');

CREATE TABLE department
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name varchar
);

INSERT INTO department (department_name)
VALUES ('First');
INSERT INTO department (department_name)
VALUES ('Second');

CREATE TABLE employee
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name_id  int REFERENCES role (id) ON DELETE SET NULL,
    department_id int REFERENCES department (id) ON DELETE SET NULL,
    name          varchar,
    surname       varchar,
    login         varchar,
    password      varchar
);

INSERT INTO employee (role_name_id, department_id, name, surname, login, password)
VALUES (1, 1, 'Bob', 'Smith', 'bob1', 'qwerty');

INSERT INTO employee (role_name_id, department_id, name, surname, login, password)
VALUES (2, 2, 'Tom', 'Jones', 'tom1', 'qwerty');

CREATE TABLE construction_type
(
    id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    construction_type varchar
);

INSERT INTO construction_type (construction_type)
VALUES ('Новая стройка');
INSERT INTO construction_type (construction_type)
VALUES ('Реконструкция');