CREATE TABLE survey_points_type
(
    id                     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    i_bcd_number           int UNIQUE,
    survey_type_short_name varchar NOT NULL,
    survey_type_full_name  varchar NOT NULL,
    additional_info        varchar
);

ALTER TABLE survey_points_type
    ADD COLUMN i_bcd_number int UNIQUE;

COMMENT ON COLUMN survey_points_type.i_bcd_number IS 'Номер из таблицы ВА. Назначение неизвестно[05.02.2023]';
COMMENT ON COLUMN survey_points_type.survey_type_short_name IS 'В таблице ВА - BCD_Name [05.02.2023]';
COMMENT ON COLUMN survey_points_type.survey_type_full_name IS 'В таблице ВА - BCD_Name_long [05.02.2023]';


INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (1, 'скв.', 'Скважины');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (2, 'т.с.з.', 'Точки статического зондирования');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (3, 'т.д.з.', 'Точки динамического зондирования');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (4, 'штам.', 'Штамповые');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (5, 'гидро.', 'Гидрогеологические');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (6, 'пресс.', 'Прессиометрические');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (7, 'ВЭЗ', 'Вертикальное электрическое зондирование');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (8, 'БТ', 'Блуждающие токи');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (9, 'ЗС', 'Зондировочные скважины');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (10, 'ТН', 'Точки наблюдения');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (11, 'ВС', 'Испытания вращательным срезом');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (12, 'шурф', 'Шурфы');

INSERT INTO survey_points_type (i_bcd_number, survey_type_short_name, survey_type_full_name)
VALUES (13, 'зак.', 'Закопушки');
