CREATE TABLE survey_point
(
    id                      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id              int     REFERENCES project (id) ON DELETE SET NULL,
    survey_point_type_id    int     REFERENCES survey_points_type (id) ON DELETE SET NULL,
    simple                  boolean,
    point_number            varchar NOT NULL,
    depth                   float4,
    depth_full_old_borehole float4,
    absolute_mark           float4,
    absolute_mark_archive   float4,
    coordinate_x            float4,
    coordinate_y            float4,
    start_date              varchar,
    end_date                varchar,
    executor_company        varchar,
    list                    varchar,
    mas                     int,
    tablet_nomenclature     varchar,
    borehole_diameter       float4,
    boring_type             varchar,
    drilling_unit_type      varchar,
    i_NFC                   int,
    f_Aq                    int,
    location_number         varchar,
    location                varchar,
    name_number             varchar,
    point_comment           varchar
);

COMMENT ON TABLE survey_point IS 'BA: CREDO_SKV [23.02.2023]';


ALTER TABLE survey_point
    ADD COLUMN simple boolean;
COMMENT ON COLUMN survey_point.simple IS 'для формуляра- простая =да (из таблицы ВА). Назначение неизвестно[05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN list varchar;
COMMENT ON COLUMN survey_point.list IS 'Лист в штамп (из таблицы ВА). Назначение неизвестно[05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN mas varchar;
COMMENT ON COLUMN survey_point.mas IS 'Масштаб чертежа (из таблицы ВА). Назначение неизвестно[05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN absolute_mark_archive varchar;
COMMENT ON COLUMN survey_point.absolute_mark_archive IS 'Абс.отм.арх. в-р. (из таблицы ВА). Назначение неизвестно[05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN depth_full_old_borehole varchar;
COMMENT ON COLUMN survey_point.depth_full_old_borehole IS 'глубина полная -для старых скважин (из таблицы ВА). Назначение неизвестно[05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN tablet_nomenclature varchar;
COMMENT ON COLUMN survey_point.tablet_nomenclature IS 'номенклатура планшета (из таблицы ВА). Назначение неизвестно[05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN borehole_diameter varchar;
COMMENT ON COLUMN survey_point.borehole_diameter IS 'Диаметр скважины [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN boring_type varchar;
COMMENT ON COLUMN survey_point.boring_type IS 'Вид бурения [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN drilling_unit_type varchar;
COMMENT ON COLUMN survey_point.drilling_unit_type IS 'Буровой агрегат [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN i_NFC varchar;
COMMENT ON COLUMN survey_point.i_NFC IS 'статус  выр-ки [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN f_Aq varchar;
COMMENT ON COLUMN survey_point.f_Aq IS 'столб воды [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN location_number varchar;
COMMENT ON COLUMN survey_point.location_number IS 'номер по экспликации - LOCATNUM (из таблицы ВА). '
    'Заполняется либо LOCATNUM либо LOCAT. Назначение неизвестно [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN location varchar;
COMMENT ON COLUMN survey_point.location IS 'Место нахожд./Арх.№ ГРИИ - LOCAT (из таблицы ВА). '
    'Заполняется либо LOCATNUM либо LOCAT. Назначение неизвестно [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN name_number varchar;
COMMENT ON COLUMN survey_point.name_number IS 'SKV_NAME, имя+ номер (таблица ВА [05.02.2023]';

ALTER TABLE survey_point
    ADD COLUMN point_comment varchar;
COMMENT ON COLUMN survey_point.point_comment IS 'Prim, примечание в колонку, в заголовке чертежа колонки (таблица ВА [05.02.2023]';

COMMENT ON COLUMN survey_point.start_date IS 'Дата начала проходки [05.02.2023]';
COMMENT ON COLUMN survey_point.end_date IS 'Дата окончания проходки [05.02.2023]';
COMMENT ON COLUMN survey_point.absolute_mark IS 'PointZ';

ALTER TABLE survey_point
    ALTER COLUMN point_number SET NOT NULL;

ALTER TABLE survey_point
DROP CONSTRAINT "survey_points_point_number_key";
