CREATE TABLE areometry
(
    id                                                   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                                            int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    particle_density                                     float4,

    is_sand                                              boolean,

    total_subsample                                      float4,
    undisturbed_sample_water_content                     float4,
    subsample_wet_soil                                   float4,

    particle_mass_over_10_mm                             float4,
    particle_mass_between_10_and_5_mm                    float4,
    particle_mass_between_5_and_2_mm                     float4,
    particle_mass_between_2_and_1_mm                     float4,
    particle_mass_between_1_and_05_mm                    float4,
    particle_mass_between_05_and_025_mm                  float4,
    particle_mass_between_025_and_01_mm                  float4,

    total_reading_for_particle_size_between_005_and_001  float4,
    total_reading_for_particle_size_between_001_and_0002 float4,
    total_reading_for_particle_size_between_less_0002    float4,
    total_reading_for_particle_size_number_three         float4,

    first_amendment                                      float4,
    second_amendment                                     float4,
    third_amendment                                      float4,
    fourth_amendment                                     float4,

    weighing_bottle_number                               varchar,
    empty_weighing_bottle_mass                           float4,
    weighing_bottle_with_wet_soil_mass                   float4,
    weighing_bottle_with_dry_soil_mass                   float4
);

COMMENT ON COLUMN areometry.total_subsample IS 'Общая навеска [16.05.2023]';
COMMENT ON COLUMN areometry.undisturbed_sample_water_content IS 'Влажность монолита [16.05.2023]';
COMMENT ON COLUMN areometry.subsample_wet_soil IS 'Навеска влажного грунта [16.05.2023]';
COMMENT ON COLUMN areometry.particle_mass_over_10_mm IS 'Вес фракции [16.05.2023]';
COMMENT ON COLUMN areometry.particle_mass_over_10_mm IS 'Размер частиц [16.05.2023]';
COMMENT ON COLUMN areometry.particle_mass_over_10_mm IS 'Поправки [16.05.2023]';
COMMENT ON COLUMN areometry.particle_mass_over_10_mm IS 'Пока задисэйблено [16.05.2023]';
