CREATE TABLE boychenko_cone
(
    id                                            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                                     int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    undisturbed_str_immersion_depth_first_measur  float4,
    undisturbed_str_immersion_depth_second_measur float4,
    undisturbed_str_immersion_depth_third_measur  float4,
    broken_str_immersion_depth_first_measur       float4,
    broken_str_immersion_depth_second_measur      float4,
    broken_str_immersion_depth_third_measur       float4,
    undisturbed_str_immersion_depth_average       float4,
    broken_str_immersion_depth_average            float4
);