CREATE TABLE construction_mesh
(
    id                             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                      int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    labor_number                   varchar,
    total_subsample                float4,
    sieve_dropper_subsample        float4,
--     Объем цилиндра
--     Объем пипетки
    pot_number                     varchar,
    pot_mass                       float4,
    pot_mass_with_sediment         float4,
    -- Y70
    mass_X_more_70                 float4,
    mass_X_70_40                   float4,
    mass_X_40_20                   float4,
    mass_X_20_10                   float4,
    mass_X_10_5                    float4,
    mass_X_5_25                    float4,
    mass_X_25_2                    float4,
    mass_X_2_125                   float4,
    mass_X_125_1                   float4,
    mass_X_1_063                   float4,
    mass_X_063_050                 float4,
    mass_X_050_0315                float4,
    mass_X_0315_025                float4,
    mass_X_025_016                 float4,
    mass_X_016_01                  float4,
--     mass_X_01_005                  float4,
--     mass_X_less_005                float4,
    HCl                            varchar
);

COMMENT ON COLUMN construction_mesh.total_subsample IS 'Общая навеска, g1 [18.06.2023]';
COMMENT ON COLUMN construction_mesh.sieve_dropper_subsample IS 'Навеска влажного грунта, g2 [18.06.2023]';
COMMENT ON COLUMN construction_mesh.pot_mass IS 'Вес тигля (авто), gam2 [18.06.2023]';
COMMENT ON COLUMN construction_mesh.pot_mass_with_sediment IS 'Вес тигля с осадком, gam1 [18.06.2023]';
COMMENT ON COLUMN construction_mesh.mass_X_more_70 IS 'Размер частиц, вес частиц, Y70 [18.06.2023]';
COMMENT ON COLUMN construction_mesh.HCl IS 'Реакция с HCl [18.06.2023]';


