CREATE TABLE density
(
    id                                                       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                                                int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    pycnometer_weight_with_dry_soil_first_measurement        float4,
    empty_pycnometer_weight_first_measurement                float4,
    pycnometer_weight_with_water_first_measurement           float4,
    pycnometer_weight_with_soil_and_water_first_measurement  float4,
    dry_soil_weight_first_measurement                        float4,
    soil_volume_first_measurement                            float4,
    soil_density_first_measurement                           float4,
    pycnometer_weight_with_dry_soil_second_measurement       float4,
    empty_pycnometer_weight_second_measurement               float4,
    pycnometer_weight_with_water_second_measurement          float4,
    pycnometer_weight_with_soil_and_water_second_measurement float4,
    dry_soil_weight_second_measurement                       float4,
    soil_volume_second_measurement                           float4,
    soil_density_second_measurement                          float4,
    average_density                                          float4
);

COMMENT
ON COLUMN density.pycnometer_weight_with_dry_soil_first_measurement IS 'ВА: X1a, Вес пикнометра с сухим грунтом [20.03.2023]';
COMMENT
ON COLUMN density.empty_pycnometer_weight_first_measurement IS 'ВА: X2a, Вес пустого пикнометра (1-е измерение) [20.03.2023]';
COMMENT
ON COLUMN density.pycnometer_weight_with_water_first_measurement IS 'ВА: X3a, Вес пикнометра с водой [20.03.2023]';
COMMENT
ON COLUMN density.pycnometer_weight_with_soil_and_water_first_measurement IS 'ВА: X4a, Вес пикнометра с грунтом и водой [20.03.2023]';
COMMENT
ON COLUMN density.dry_soil_weight_first_measurement IS 'ВА: X12a, Вес сухого грунта [20.03.2023]';
COMMENT
ON COLUMN density.soil_volume_first_measurement IS 'ВА: Va, Объем грунта [20.03.2023]';
COMMENT
ON COLUMN density.soil_density_first_measurement IS 'ВА: Roa, Плотность грунта [20.03.2023]';
COMMENT
ON COLUMN density.pycnometer_weight_with_dry_soil_second_measurement IS 'ВА: X1b, Вес пикнометра с сухим грунтом (2-е измерение) [20.03.2023]';
COMMENT
ON COLUMN density.empty_pycnometer_weight_second_measurement IS 'ВА: X2b, Вес пустого пикнометра [20.03.2023]';
COMMENT
ON COLUMN density.pycnometer_weight_with_water_second_measurement IS 'ВА: X3b, Вес пикнометра с водой [20.03.2023]';
COMMENT
ON COLUMN density.pycnometer_weight_with_soil_and_water_second_measurement IS 'ВА: X4b, Вес пикнометра с грунтом и водой [20.03.2023]';
COMMENT
ON COLUMN density.dry_soil_weight_second_measurement IS 'ВА: X12b, Вес сухого грунта [20.03.2023]';
COMMENT
ON COLUMN density.soil_volume_second_measurement IS 'ВА: Vb, Объем грунта [20.03.2023]';
COMMENT
ON COLUMN density.soil_density_second_measurement IS 'ВА: Rob, Плотность грунта [20.03.2023]';
COMMENT
ON COLUMN density.average_density IS 'BA: DensityAver, Средняя плотность (по двум записям из табл Density). [25.02.2023]';
