CREATE TABLE gran_composition_areometry
(
    id                          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                   int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    included_more_2             float4,
    X_more_10                   float4,
    X_10_5_old_10_2             float4,
    X_5_2                       float4,
    X_2_1                       float4,
    X_1_05                      float4,
    X_05_025                    float4,
    X_025_01                    float4,
    X_01_005                    float4,
    X_005_001                   float4,
    X_001_0002_old_001_0005     float4,
    X_0005_0002                 float4,
    X_less_0002                 float4,
    sum_2_005                   float4,
    sum_005_0002_old_005_0005   float4,
    sum_less_0002_old_less_0005 float4,
    soil_kind                   varchar,
    uniformity_coefficient      float4,
    uniformity_degree           varchar,
    HCl                         float4,
    dispersity_index            float4,
    heaving_degree              varchar

);

ALTER TABLE gran_composition_areometry ADD FOREIGN KEY REFERENCES survey_point (id) ON DELETE SET NULL;

COMMENT ON COLUMN gran_composition_areometry.X_more_10 IS 'Обозначение по ГОСТ. Зерновой состав в % при размере частиц в мм. [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.sum_2_005 IS 'Сумма фракций, %. [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.soil_kind IS 'Разновидность грунта (рассчитывается в ареометрии) [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.uniformity_coefficient IS 'Коэффициент неоднородности [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.uniformity_degree IS 'Степень неоднородности [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.HCl IS 'Реакция с HCl [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.dispersity_index IS 'Показатель дисперсности [24.05.2023]';
COMMENT ON COLUMN gran_composition_areometry.heaving_degree IS 'Наименование дисперсности [24.05.2023]';