CREATE TABLE gran_composition_construction_mesh
(
    id                          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                   int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,

    X_more_70                      float4,
    X_70_40                        float4,
    X_40_20                        float4,
    X_20_10                        float4,
    X_10_5                         float4,
    X_5_25                         float4,
    X_25_2                         float4,
    X_2_125                        float4,
    X_125_1                        float4,
    X_1_063                        float4,
    X_063_050                      float4,
    X_050_0315                     float4,
    X_0315_025                     float4,
    X_025_016                      float4,
    X_016_01                       float4,
    X_01_005                       float4,
    X_less_005                     float4,
    correction                     float4,
    soil_kind                      varchar,
    uniformity_coefficient         float4,
    uniformity_degree              varchar,
    fineness_modulus               float4,
    sand_group_by_fineness_modulus varchar,
    lenses_and_seams               varchar
);


COMMENT ON COLUMN gran_composition_construction_mesh.X_more_70 IS 'Зерновой состав в % при размере частиц в мм, Y70 [18.06.2023]';
COMMENT ON COLUMN gran_composition_construction_mesh.uniformity_coefficient IS 'Коэффициент неоднородности, Cn [18.06.2023]';
COMMENT ON COLUMN gran_composition_construction_mesh.uniformity_degree IS 'Степень неоднородности, Stn [18.06.2023]';
COMMENT ON COLUMN gran_composition_construction_mesh.fineness_modulus IS 'Модуль крупности песка, Mk [18.06.2023]';
COMMENT ON COLUMN gran_composition_construction_mesh.sand_group_by_fineness_modulus IS 'Группа песка по модулю крупности, GMk [18.06.2023]';
COMMENT ON COLUMN gran_composition_construction_mesh.lenses_and_seams IS 'Линзы и прослои, LP [18.06.2023]';