CREATE TABLE organic_matter
(
    id                                              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                                       int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    empty_pot_mass_first_measurement                float4,
    empty_pot_mass_second_measurement               float4,
    absolutely_dry_soil_pot_mass_first_measurement  float4,
    absolutely_dry_soil_pot_mass_second_measurement float4,
    calcined_soil_pot_mass_first_measurement        float4,
    calcined_soil_pot_mass_second_measurement       float4,
    ignition_loss_mass_first_measurement            float4,
    ignition_loss_mass_second_measurement           float4,
    dry_matter_content_before                       float4,
    dry_matter_content_after                        float4,
    ignition_loss_average_mass                      float4,
    ash_content                                     float4,
    P250                                            float4,
    decomposition_degree                            float4
);

COMMENT ON COLUMN organic_matter.empty_pot_mass_first_measurement IS 'Вес пустого тигля. [30.04.2023]';
COMMENT ON COLUMN organic_matter.empty_pot_mass_second_measurement IS 'Вес пустого тигля. [30.04.2023]';
COMMENT ON COLUMN organic_matter.absolutely_dry_soil_pot_mass_first_measurement IS 'Вес тигля с абс. сухим грунтом. [30.04.2023]';
COMMENT ON COLUMN organic_matter.absolutely_dry_soil_pot_mass_second_measurement IS 'Вес тигля с абс. сухим грунтом. [30.04.2023]';
COMMENT ON COLUMN organic_matter.calcined_soil_pot_mass_first_measurement IS 'Вес тигля с прокаленным грунтом. [30.04.2023]';
COMMENT ON COLUMN organic_matter.calcined_soil_pot_mass_second_measurement IS 'Вес тигля с прокаленным грунтом. [30.04.2023]';
COMMENT ON COLUMN organic_matter.ignition_loss_mass_first_measurement IS 'Потери при прокаливании. [30.04.2023]';
COMMENT ON COLUMN organic_matter.ignition_loss_mass_second_measurement IS 'Потери при прокаливании. [30.04.2023]';
COMMENT ON COLUMN organic_matter.dry_matter_content_before IS 'Доля сухого в-ва. [30.04.2023]';
COMMENT ON COLUMN organic_matter.dry_matter_content_after IS 'Доля сухого в-ва. [30.04.2023]';
COMMENT ON COLUMN organic_matter.ash_content IS 'Зольность,%. [30.04.2023]';
COMMENT ON COLUMN organic_matter.P250 IS '? [30.04.2023]';
COMMENT ON COLUMN organic_matter.decomposition_degree IS 'Степень разложения,%. [30.04.2023]';
