CREATE TABLE physical_properties
(
    id                                                     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                                              int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    labor_number                                           varchar,
    average_density                                        float4,
    ring_density_average                                   float4,
    ring_dry_soil_density                                  float4,
    void_ratio                                             float4,
    natural_average_water_content                          float4,
    saturation_ratio                                       float4,
    full_moisture_capacity                                 float4,
    average_liquid_limit                                   float4,
    plastic_limit                                          float4,
    plasticity_index                                       float4,
    plasticity_soil_sub_type                               varchar,
    liquidity_index                                        float4,
    liquidity_soil_sub_type                                varchar,
    clay_soil_sub_type                                     varchar,
    undisturbed_str_boychenko_cone_immersion_depth_average float4,
    undisturbed_structure_cb_liquidity_index_name          varchar,
    undisturbed_structure_cb_consistency                   float4,
    broken_str_boychenko_cone_immersion_depth_average      float4,
    broken_structure_cb_liquidity_index_name               varchar,
    broken_structure_cb_consistency                        float4,
    cb_consistency_difference                              float4,
    structural_strength_degree                             varchar,
    ignition_loss_average_mass                             float4,
    ignition_loss_average_name                             varchar,
    decomposition_degree                                   float4,
    decomposition_degree_name                              varchar

-- todo.txt нейминг + коррозионный метод
--     Корроз. агр. грунта, Om*m
--     Корроз. агр. грунта, Om*m
--     Корроз. агр. грунта, A/m^2
--     Корроз. агр. грунта, A/m^2
);


COMMENT
    ON COLUMN physical_properties.average_density IS 'Плотность частиц грунта (г/см3) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.ring_density_average IS 'Плотность грунта (г/см3) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.ring_dry_soil_density IS 'Плотность скелета грунта (г/см3) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.void_ratio IS 'Коэффициент пористости (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.natural_average_water_content IS 'Природная влажность (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.saturation_ratio IS 'Коэффициент водонасыщения [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.full_moisture_capacity IS 'Полная влагоемкость (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.average_liquid_limit IS 'Влажность на границе текучести (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.plastic_average_water_content IS 'Влажность на границе пластичности (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.plasticity_index IS 'Число пластичности (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.plasticity_soil_sub_type IS 'Разновидность [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.liquidity_index IS 'Показатель текучести (доли ед.) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.liquidity_soil_sub_type IS 'Разновидность (консистенция) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.clay_soil_sub_type IS 'Разновидность глинистых грунтов [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.undisturbed_str_boychenko_cone_immersion_depth_average IS 'Глубина погружения конуса Бойченко при ненарушенной стр-ре (мм) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.undisturbed_structure_cb_liquidity_index_name IS 'Показатель текучести по Cb при ненарушенной стр-ре [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.undisturbed_structure_cb_consistency IS 'Консистенция по Cb при ненарушенной стр-ре (Cut | Paraffin) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.broken_str_boychenko_cone_immersion_depth_average IS 'Глубина погружения конуса Бойченко при нарушенной стр-ре (мм) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.broken_structure_cb_liquidity_index_name IS 'Показатель текучести по Cb при нарушенной стр-ре [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.broken_structure_cb_consistency IS 'Консистенция по Cb при нарушенной стр-ре (Cut | Paraffin) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.cb_consistency_difference IS 'Разница показателей текучести (используется, но не нашел в базе) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.structural_strength_degree IS 'Степень выраженности структурных свойств (используется, но не нашел в базе) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.ignition_loss_average_mass IS 'Отн. содержание орг. в-ва (Потери при прокаливании (среднее)) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.ignition_loss_average_name IS 'Наименование по отн. содержанию орг. в-ва [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.decomposition_degree IS 'Степень разложения торфа (%) [11.06.2023]';
COMMENT
    ON COLUMN physical_properties.decomposition_degree_name IS 'Наименование по степени разложения торфа [11.06.2023]';

ALTER TABLE physical_properties
    ADD COLUMN plastic_limit float4;
COMMENT ON COLUMN physical_properties.plastic_limit IS 'Влажность на границе пластичности (доли ед.)';