CREATE TABLE ring_density
(
    id                                         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id                                  int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    ring_number_first_measurement              varchar,
    ring_number_second_measurement             varchar,
    empty_ring_mass_first_measurement          float4,
    empty_ring_mass_second_measurement         float4,
    ring_with_wet_soil_mass_first_measurement  float4,
    ring_with_wet_soil_mass_second_measurement float4,
    ring_volume_first_measurement              float4,
    ring_volume_second_measurement             float4,
    ring_density_first_measurement             float4,
    ring_density_second_measurement            float4,
    ring_density_average                       float4,
    ring_dry_soil_density                      float4,
    full_water_content                         float4,
    saturation_ratio                           float4,

    void_ratio                                 float4
);


COMMENT
ON COLUMN ring_density.ring_dry_soil_density IS 'Плотность скелета. [19.04.2023]';
-- удалено из таблицы и сущности:
COMMENT
ON COLUMN ring_density.ring_particle_density IS 'Плотность частиц грунта. [19.04.2023]';
COMMENT
ON COLUMN ring_density.full_water_content IS 'Полная влагоемкость. [19.04.2023]';

ALTER TABLE ring_density
    ADD COLUMN saturation_ratio float4;
COMMENT
ON COLUMN ring_density.saturation_ratio IS 'ВА: Sr, Коэффициент водонасыщения (Cut | Paraffin) [08.03.2023]';


ALTER TABLE ring_density
    ADD COLUMN void_ratio float4;
COMMENT
ON COLUMN ring_density.void_ratio IS 'Коэффициент пористости [08.03.2023]';
