CREATE TABLE water_content
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,
    natural_water_content_weighing_bottle_number_first_measurement  varchar,
    natural_water_content_weighing_bottle_number_second_measurement varchar,
    liquidity_weighing_bottle_number_first_measurement              varchar,
    liquidity_weighing_bottle_number_second_measurement             varchar,
    plastic_weighing_bottle_number_first_measurement                varchar,
    plastic_weighing_bottle_number_second_measurement               varchar,

    natural_water_content_empty_weighing_bottle_mass_first_measur   float4,
    natural_water_content_empty_weighing_bottle_mass_second_measur  float4,
    liquidity_empty_weighing_bottle_mass_first_measurement          float4,
    liquidity_empty_weighing_bottle_mass_second_measurement         float4,
    plastic_empty_weighing_bottle_mass_first_measurement            float4,
    plastic_empty_weighing_bottle_mass_second_measurement           float4,
    natural_water_content_weighing_bottle_with_wet_soil_mass_first  float4,
    natural_water_content_weighing_bottle_with_wet_soil_mass_second float4,
    liquidity_weighing_bottle_with_wet_soil_mass_first              float4,
    liquidity_weighing_bottle_with_wet_soil_mass_second             float4,
    plastic_weighing_bottle_with_wet_soil_mass_first                float4,
    plastic_weighing_bottle_with_wet_soil_mass_second               float4,
    natural_water_content_weighing_bottle_with_dry_soil_mass_first  float4,
    natural_water_content_weighing_bottle_with_dry_soil_mass_second float4,
    liquidity_weighing_bottle_with_dry_soil_mass_first              float4,
    liquidity_weighing_bottle_with_dry_soil_mass_second             float4,
    plastic_weighing_bottle_with_dry_soil_mass_first                float4,
    plastic_weighing_bottle_with_dry_soil_mass_second               float4,
    natural_water_content_weighing_bottle_water_content_first       float4,
    natural_water_content_weighing_bottle_water_content_second      float4,
    liquidity_weighing_bottle_water_content_first                   float4,
    liquidity_weighing_bottle_water_content_second                  float4,
    plastic_weighing_bottle_water_content_first                     float4,
    plastic_weighing_bottle_water_content_second                    float4,
    natural_water_content_average_water_content                     float4,
    average_liquid_limit                                 float4,
    average_plastic_limit                                   float4,
    plasticity_index                                                float4,
    liquidity_index                                                 float4
);

COMMENT ON COLUMN water_content.natural_water_content_weighing_bottle_number_first_measurement IS 'Естественная влажность. Номер бюкса. Первое измерение [09.04.2023]';
COMMENT ON COLUMN water_content.natural_water_content_weighing_bottle_number_second_measurement IS 'Естественная влажность. Номер бюкса. Второе измерение [09.04.2023]';
COMMENT ON COLUMN water_content.liquidity_weighing_bottle_number_first_measurement IS 'Влажность на границе текучести. Номер бюкса. Первое измерение [09.04.2023]';
COMMENT ON COLUMN water_content.liquidity_weighing_bottle_number_second_measurement IS 'Влажность на границе текучести. Номер бюкса. Второе измерение [09.04.2023]';
COMMENT ON COLUMN water_content.plastic_weighing_bottle_number_first_measurement IS 'Влажность на границе раската. Номер бюкса. Первое измерение [09.04.2023]';
COMMENT ON COLUMN water_content.plastic_weighing_bottle_number_second_measurement IS 'Влажность на границе раската. Номер бюкса. Второе измерение [09.04.2023]';
COMMENT ON COLUMN water_content.natural_water_content_empty_weighing_bottle_mass_first_measur IS 'ВА: X1_a, Вес пустого бюкса [09.04.2023]';
COMMENT ON COLUMN water_content.natural_water_content_empty_weighing_bottle_mass_second_measur IS 'ВА: X1_b, Вес пустого бюкса [09.04.2023]';
COMMENT ON COLUMN water_content.liquidity_empty_weighing_bottle_mass_first_measurement IS 'ВА: Y1_a, Вес пустого бюкса [09.04.2023]';
COMMENT ON COLUMN water_content.liquidity_empty_weighing_bottle_mass_second_measurement IS 'ВА: Y1_b, Вес пустого бюкса [09.04.2023]';
COMMENT ON COLUMN water_content.plastic_empty_weighing_bottle_mass_first_measurement IS 'ВА: Z1_a, Вес пустого бюкса [09.04.2023]';
COMMENT ON COLUMN water_content.plastic_empty_weighing_bottle_mass_second_measurement IS 'ВА: Z1_b, Вес пустого бюкса [09.04.2023]';



--todo.txt заменить на: average water content
ALTER TABLE sample
    ADD COLUMN natural_water_content_average_water_content float4;