CREATE TABLE water_extract_partial
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id     int NOT NULL REFERENCES sample (id) ON DELETE SET NULL,

    is_archive    boolean,
    is_blocked    boolean,

    depth_from    float4,
    depth_to      float4,
    sampling_date date,

    pH            float4,
    Cl_1          float4,
    Cl_2          float4,
    NO3           float4,
    Fe            float4,
    gum_1         float4,
    gum_2         float4,
    SO4_1         float4,
    SO4_2         float4,

    cl_coef         float4
)