CREATE TABLE CL_COLOR
(
--  У ВА это CLT_ID
    ID             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

-- TODO: ???
    CL_ID int,

    CLT_NAME       VARCHAR,
    CLT_DATA        VARCHAR,

    STATUS         varchar,
    CREATOR        VARCHAR,
    DATE_CR        varchar,
    ARCHIVER       VARCHAR,
    DATE_ARCH      varchar
);


