CREATE TABLE CL_SOIL_SUBKIND
(
    ID          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SKGT_ID     int NOT NULL REFERENCES CL_SOIL_KIND_GROUP_TYPE (id) ON DELETE SET NULL,
    CLT_ID      int,
    SS_NAME     VARCHAR,
    SS_ENABLE   boolean,
    STATUS      varchar,
    CREATOR     VARCHAR,
    DATE_CR     varchar,
    ARCHIVER    VARCHAR,
    DATE_ARCH   varchar,

    SS_FC_R     int,
    SS_FC_G     int,
    SS_FC_B     int,
    CLT_BORE_ID int,
    SS_DESCR    varchar,

    SS_OTM      boolean,

    -- штриховка тисиз  из тбл Global_SGR:
    ACAD        VARCHAR
);

-- ALTER TABLE CL_SOIL_CLASS RENAME COLUMN sc_id TO id;

COMMENT ON COLUMN CL_SOIL_SUBKIND.ACAD
    IS 'BA: штриховка тисиз  из тбл Global_SGR. [12.11.2023]';
