CREATE TABLE CL_SOIL_KIND
(
    ID             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SC_ID          int NOT NULL REFERENCES CL_SOIL_CLASS (id) ON DELETE SET NULL,
    CLT_ID         int,
    SK_GROUP       VARCHAR,
    SK_SUBGROUP1   VARCHAR,
    SK_SUBGROUP2   VARCHAR,
    SK_TYPE1       VARCHAR,
    SK_TYPE2       VARCHAR,
    SK_KIND        VARCHAR,
    SK_ENABLE      INT,
    STATUS         varchar,
    CREATOR        VARCHAR,
    DATE_CR        varchar,
    ARCHIVER       VARCHAR,
    DATE_ARCH      varchar,
    SK_BASE_ENABLE int,
    SK_DESCR       varchar
);

-- ALTER TABLE CL_SOIL_CLASS RENAME COLUMN sc_id TO id;

