CREATE TABLE classif_soil_class_kind_group
(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soil_kind_group varchar,
    soil_class_id   int NOT NULL REFERENCES CL_SOIL_CLASS (id) ON DELETE SET NULL
);

COMMENT ON TABLE classif_soil_class_kind_group IS 'Таблица для уникальных sk_group для вывода в чойсбоксе soilKindChoiceBox';

-- ALTER TABLE classif_soil_class_kind_group DROP CONSTRAINT

ALTER TABLE classif_soil_class_kind_group
    DROP CONSTRAINT classif_soil_class_kind_group_soil_kind_group_key;

SELECT *
FROM information_schema.constraint_table_usage
WHERE table_name = 'classif_soil_class_kind_group';